import { useCallback, useMemo } from 'react'
import type { Node } from '@xyflow/react'
import { useTranslation } from '@app/renderer/i18n'
import type { TerminalNodeData } from '../../../types'
import type { ContextMenuState, ShowWorkspaceCanvasMessage } from '../types'

type SetNodes = (
  updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
  options?: { syncLayout?: boolean },
) => void

function resolveFallbackTaskTitle(requirement: string): string {
  const cleanedRequirement = requirement.replace(/\s+/g, ' ').trim()
  if (cleanedRequirement.length === 0) {
    return 'New task'
  }

  if (cleanedRequirement.length <= 24) {
    return cleanedRequirement
  }

  return `${cleanedRequirement.slice(0, 24)}...`
}

export function useWorkspaceCanvasNoteToTaskConversion({
  selectedNodeIds,
  selectedNodeIdsRef,
  flowNodes,
  nodesRef,
  setNodes,
  onRequestPersistFlush,
  onShowMessage,
  setContextMenu,
}: {
  selectedNodeIds: string[]
  selectedNodeIdsRef: React.MutableRefObject<string[]>
  flowNodes: Node<TerminalNodeData>[]
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  setNodes: SetNodes
  onRequestPersistFlush?: () => void
  onShowMessage?: ShowWorkspaceCanvasMessage
  setContextMenu: React.Dispatch<React.SetStateAction<ContextMenuState | null>>
}): {
  canConvertSelectedNoteToTask: boolean
  isConvertSelectedNoteToTaskDisabled: boolean
  convertSelectedNoteToTask: () => void
} {
  const { t } = useTranslation()
  const selectedNoteMeta = useMemo(() => {
    if (selectedNodeIds.length !== 1) {
      return { canConvert: false, isDisabled: false }
    }

    const selectedId = selectedNodeIds[0]
    const selected = flowNodes.find(node => node.id === selectedId) ?? null

    if (!selected || selected.data.kind !== 'note') {
      return { canConvert: false, isDisabled: false }
    }

    const text = selected.data.note?.text ?? ''
    return { canConvert: true, isDisabled: text.trim().length === 0 }
  }, [flowNodes, selectedNodeIds])

  const convertSelectedNoteToTask = useCallback(() => {
    const selectedIds = selectedNodeIdsRef.current
    if (selectedIds.length !== 1) {
      setContextMenu(null)
      return
    }

    const nodeId = selectedIds[0]
    const selected = nodesRef.current.find(node => node.id === nodeId) ?? null
    if (!selected || selected.data.kind !== 'note' || !selected.data.note) {
      setContextMenu(null)
      return
    }

    const requirement = selected.data.note.text.trim()
    if (requirement.length === 0) {
      onShowMessage?.(t('messages.noteToTaskRequiresContent'), 'warning')
      return
    }

    const title = resolveFallbackTaskTitle(requirement)
    const now = new Date().toISOString()

    setNodes(
      prevNodes => {
        let hasChanged = false
        const nextNodes = prevNodes.map(node => {
          if (node.id !== nodeId || node.data.kind !== 'note' || !node.data.note) {
            return node
          }

          hasChanged = true

          return {
            ...node,
            type: 'taskNode',
            selectable: true,
            data: {
              ...node.data,
              title,
              kind: 'task',
              task: {
                requirement,
                status: 'todo',
                priority: 'medium',
                tags: [],
                linkedAgentNodeId: null,
                agentSessions: [],
                lastRunAt: null,
                autoGeneratedTitle: false,
                createdAt: now,
                updatedAt: now,
              },
              note: null,
            },
          }
        })

        return hasChanged ? nextNodes : prevNodes
      },
      { syncLayout: false },
    )

    onRequestPersistFlush?.()
    setContextMenu(null)
  }, [
    nodesRef,
    onRequestPersistFlush,
    onShowMessage,
    selectedNodeIdsRef,
    setContextMenu,
    setNodes,
    t,
  ])

  return {
    canConvertSelectedNoteToTask: selectedNoteMeta.canConvert,
    isConvertSelectedNoteToTaskDisabled: selectedNoteMeta.isDisabled,
    convertSelectedNoteToTask,
  }
}
