import type { Node } from '@xyflow/react'
import type { Point, Size, TerminalNodeData, TaskPriority } from '../../../types'
import type { WorkspaceSpaceState } from '../../../types'
import type { CreateNodeInput } from '../types'

export interface UseWorkspaceCanvasNodesStoreParams {
  nodes: Node<TerminalNodeData>[]
  spacesRef: React.MutableRefObject<WorkspaceSpaceState[]>
  onNodesChange: (nodes: Node<TerminalNodeData>[]) => void
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onRequestPersistFlush?: () => void
  onShowMessage?: (message: string) => void
  defaultTerminalWindowScalePercent: number
}

export interface UseWorkspaceCanvasNodesStoreResult {
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  pendingScrollbackByNodeRef: React.MutableRefObject<Map<string, string>>
  isNodeDraggingRef: React.MutableRefObject<boolean>
  setNodes: (
    updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    options?: { syncLayout?: boolean },
  ) => void
  upsertNode: (nextNode: Node<TerminalNodeData>) => void
  bumpAgentLaunchToken: (nodeId: string) => number
  clearAgentLaunchToken: (nodeId: string) => void
  isAgentLaunchTokenCurrent: (nodeId: string, token: number) => boolean
  closeNode: (nodeId: string) => Promise<void>
  normalizePosition: (nodeId: string, desired: Point, size: Size) => Point
  resizeNode: (nodeId: string, desiredSize: Size) => void
  applyPendingScrollbacks: (targetNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[]
  updateNodeScrollback: (nodeId: string, scrollback: string) => void
  updateTerminalTitle: (nodeId: string, title: string) => void
  renameTerminalTitle: (nodeId: string, title: string) => void
  updateNoteText: (nodeId: string, text: string) => void
  createNodeForSession: (input: CreateNodeInput) => Promise<Node<TerminalNodeData> | null>
  createNoteNode: (anchor: Point) => Node<TerminalNodeData> | null
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
  ) => Node<TerminalNodeData> | null
}
