import { useCallback, useEffect, useState, type MutableRefObject } from 'react'
import type { Node } from '@xyflow/react'
import { useTranslation } from '@app/renderer/i18n'
import { AI_NAMING_FEATURES } from '@shared/featureFlags/aiNaming'
import type { TaskPriority, TerminalNodeData } from '../../../types'
import { normalizeTaskTagSelection, toErrorMessage } from '../helpers'
import type { ContextMenuState, TaskEditorState } from '../types'

interface UseTaskEditorParams {
  nodesRef: MutableRefObject<Node<TerminalNodeData>[]>
  setNodes: (
    updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    options?: { syncLayout?: boolean },
  ) => void
  onRequestPersistFlush?: () => void
  setContextMenu: React.Dispatch<React.SetStateAction<ContextMenuState | null>>
  suggestTaskTitle: (
    requirement: string,
  ) => Promise<{ title: string; priority: TaskPriority; tags: string[] }>
  taskTagOptions: string[]
  openTaskEditorRef: MutableRefObject<(nodeId: string) => void>
}

export function useWorkspaceCanvasTaskEditor({
  nodesRef,
  setNodes,
  onRequestPersistFlush,
  setContextMenu,
  suggestTaskTitle,
  taskTagOptions,
  openTaskEditorRef,
}: UseTaskEditorParams): {
  taskEditor: TaskEditorState | null
  setTaskEditor: React.Dispatch<React.SetStateAction<TaskEditorState | null>>
  closeTaskEditor: () => void
  generateTaskEditorTitle: () => Promise<void>
  saveTaskEdits: () => Promise<void>
} {
  const { t } = useTranslation()
  const [taskEditor, setTaskEditor] = useState<TaskEditorState | null>(null)
  const isTaskAiNamingEnabled = AI_NAMING_FEATURES.taskTitleGeneration

  const closeTaskEditor = useCallback(() => {
    setTaskEditor(prev => {
      if (!prev || prev.isSaving || prev.isGeneratingTitle) {
        return prev
      }

      return null
    })
  }, [])

  const openTaskEditor = useCallback(
    (nodeId: string) => {
      const node = nodesRef.current.find(item => item.id === nodeId)
      if (!node || node.data.kind !== 'task' || !node.data.task) {
        return
      }

      setTaskEditor({
        nodeId,
        initialTitle: node.data.title,
        initialAutoGeneratedTitle: node.data.task.autoGeneratedTitle,
        titleGeneratedInEditor: false,
        title: node.data.title,
        requirement: node.data.task.requirement,
        priority: node.data.task.priority,
        selectedTags: node.data.task.tags,
        autoGenerateTitle: isTaskAiNamingEnabled && node.data.task.autoGeneratedTitle,
        isGeneratingTitle: false,
        isSaving: false,
        error: null,
      })

      setContextMenu(null)
    },
    [isTaskAiNamingEnabled, nodesRef, setContextMenu],
  )

  const generateTaskEditorTitle = useCallback(async () => {
    if (!taskEditor) {
      return
    }

    if (!isTaskAiNamingEnabled) {
      return
    }

    const requirement = taskEditor.requirement.trim()
    if (requirement.length === 0) {
      setTaskEditor(prev =>
        prev
          ? {
              ...prev,
              error: t('messages.taskRequirementRequired'),
            }
          : prev,
      )
      return
    }

    setTaskEditor(prev =>
      prev
        ? {
            ...prev,
            isGeneratingTitle: true,
            error: null,
          }
        : prev,
    )

    try {
      const suggestion = await suggestTaskTitle(requirement)
      setTaskEditor(prev =>
        prev
          ? {
              ...prev,
              title: suggestion.title,
              priority: suggestion.priority,
              selectedTags: suggestion.tags,
              titleGeneratedInEditor: true,
              isGeneratingTitle: false,
              error: null,
            }
          : prev,
      )
    } catch (error) {
      setTaskEditor(prev =>
        prev
          ? {
              ...prev,
              isGeneratingTitle: false,
              error: t('messages.taskTitleGenerateFailed', { message: toErrorMessage(error) }),
            }
          : prev,
      )
    }
  }, [isTaskAiNamingEnabled, suggestTaskTitle, t, taskEditor])

  const saveTaskEdits = useCallback(async () => {
    if (!taskEditor) {
      return
    }

    const requirement = taskEditor.requirement.trim()
    let title = taskEditor.title.trim()
    let priority = taskEditor.priority
    let selectedTags = normalizeTaskTagSelection(taskEditor.selectedTags, taskTagOptions)

    if (requirement.length === 0) {
      setTaskEditor(prev =>
        prev
          ? {
              ...prev,
              error: t('messages.taskRequirementRequired'),
            }
          : prev,
      )
      return
    }

    setTaskEditor(prev =>
      prev
        ? {
            ...prev,
            isSaving: true,
            error: null,
          }
        : prev,
    )

    let autoGeneratedTitle = taskEditor.initialAutoGeneratedTitle

    try {
      if (title.length === 0) {
        if (!isTaskAiNamingEnabled || !taskEditor.autoGenerateTitle) {
          setTaskEditor(prev =>
            prev
              ? {
                  ...prev,
                  isSaving: false,
                  error: isTaskAiNamingEnabled
                    ? t('messages.taskTitleOrAutoGenerateRequired')
                    : t('messages.taskTitleRequired'),
                }
              : prev,
          )
          return
        }

        const suggestion = await suggestTaskTitle(requirement)
        title = suggestion.title
        priority = suggestion.priority
        selectedTags = suggestion.tags
        autoGeneratedTitle = true
      } else if (title !== taskEditor.initialTitle) {
        autoGeneratedTitle = taskEditor.titleGeneratedInEditor
      }

      const now = new Date().toISOString()

      setNodes(prevNodes =>
        prevNodes.map(node => {
          if (node.id !== taskEditor.nodeId || node.data.kind !== 'task' || !node.data.task) {
            return node
          }

          return {
            ...node,
            data: {
              ...node.data,
              title,
              lastError: null,
              task: {
                ...node.data.task,
                requirement,
                priority,
                tags: selectedTags,
                autoGeneratedTitle,
                updatedAt: now,
              },
            },
          }
        }),
      )

      onRequestPersistFlush?.()
      setTaskEditor(null)
    } catch (error) {
      setTaskEditor(prev =>
        prev
          ? {
              ...prev,
              isSaving: false,
              error: t('messages.taskUpdateFailed', { message: toErrorMessage(error) }),
            }
          : prev,
      )
    }
  }, [
    isTaskAiNamingEnabled,
    onRequestPersistFlush,
    setNodes,
    suggestTaskTitle,
    t,
    taskEditor,
    taskTagOptions,
  ])

  useEffect(() => {
    openTaskEditorRef.current = nodeId => {
      openTaskEditor(nodeId)
    }
  }, [openTaskEditor, openTaskEditorRef])

  return {
    taskEditor,
    setTaskEditor,
    closeTaskEditor,
    generateTaskEditorTitle,
    saveTaskEdits,
  }
}
