import { useCallback, useState } from 'react'
import type { Node } from '@xyflow/react'
import type { Point, TaskPriority, TerminalNodeData, WorkspaceSpaceState } from '../../../types'
import { normalizeTaskTagSelection, sanitizeSpaces, toErrorMessage } from '../helpers'
import type { ContextMenuState, TaskCreatorState } from '../types'
import { expandSpaceToFitOwnedNodesAndPushAway } from '../../../utils/spaceAutoResize'

type SetNodes = (
  updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
  options?: { syncLayout?: boolean },
) => void

interface UseTaskCreatorParams {
  contextMenu: ContextMenuState | null
  setContextMenu: React.Dispatch<React.SetStateAction<ContextMenuState | null>>
  taskTagOptions: string[]
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  setNodes: SetNodes
  spacesRef: React.MutableRefObject<WorkspaceSpaceState[]>
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onRequestPersistFlush?: () => void
  suggestTaskTitle: (
    requirement: string,
  ) => Promise<{ title: string; priority: TaskPriority; tags: string[] }>
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
  ) => Node<TerminalNodeData> | null
}

export function useWorkspaceCanvasTaskCreator({
  contextMenu,
  setContextMenu,
  taskTagOptions,
  nodesRef,
  setNodes,
  spacesRef,
  onSpacesChange,
  onRequestPersistFlush,
  suggestTaskTitle,
  createTaskNode,
}: UseTaskCreatorParams): {
  taskCreator: TaskCreatorState | null
  setTaskCreator: React.Dispatch<React.SetStateAction<TaskCreatorState | null>>
  openTaskCreator: () => void
  closeTaskCreator: () => void
  generateTaskTitle: () => Promise<void>
  createTask: () => Promise<void>
} {
  const [taskCreator, setTaskCreator] = useState<TaskCreatorState | null>(null)

  const fallbackTaskTitle = useCallback((requirement: string): string => {
    const cleaned = requirement.replace(/\s+/g, ' ').trim()
    if (cleaned.length === 0) {
      return 'New task'
    }

    if (cleaned.length <= 24) {
      return cleaned
    }

    return `${cleaned.slice(0, 24)}...`
  }, [])

  const openTaskCreator = useCallback(() => {
    if (!contextMenu || contextMenu.kind !== 'pane') {
      return
    }

    setTaskCreator({
      anchor: {
        x: contextMenu.flowX,
        y: contextMenu.flowY,
      },
      title: '',
      requirement: '',
      priority: 'medium',
      selectedTags: [],
      autoGenerateTitle: true,
      isGeneratingTitle: false,
      isCreating: false,
      error: null,
    })

    setContextMenu(null)
  }, [contextMenu, setContextMenu])

  const closeTaskCreator = useCallback(() => {
    setTaskCreator(prev => {
      if (!prev || prev.isCreating || prev.isGeneratingTitle) {
        return prev
      }

      return null
    })
  }, [])

  const generateTaskTitle = useCallback(async () => {
    if (!taskCreator) {
      return
    }

    const requirement = taskCreator.requirement.trim()
    if (requirement.length === 0) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              error: '任务要求不能为空。',
            }
          : prev,
      )
      return
    }

    setTaskCreator(prev =>
      prev
        ? {
            ...prev,
            isGeneratingTitle: true,
            error: null,
          }
        : prev,
    )

    try {
      const suggestion = await suggestTaskTitle(requirement)
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              title: suggestion.title,
              priority: suggestion.priority,
              selectedTags: suggestion.tags,
              isGeneratingTitle: false,
              error: null,
            }
          : prev,
      )
    } catch (error) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              isGeneratingTitle: false,
              error: `自动生成失败：${toErrorMessage(error)}`,
            }
          : prev,
      )
    }
  }, [suggestTaskTitle, taskCreator])

  const createTask = useCallback(async () => {
    if (!taskCreator) {
      return
    }

    const requirement = taskCreator.requirement.trim()
    const titleInput = taskCreator.title.trim()
    let priority = taskCreator.priority
    let selectedTags = normalizeTaskTagSelection(taskCreator.selectedTags, taskTagOptions)

    if (requirement.length === 0) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              error: '任务要求不能为空。',
            }
          : prev,
      )
      return
    }

    setTaskCreator(prev =>
      prev
        ? {
            ...prev,
            isCreating: true,
            error: null,
          }
        : prev,
    )

    try {
      const title = titleInput.length > 0 ? titleInput : fallbackTaskTitle(requirement)

      const created = createTaskNode(
        taskCreator.anchor,
        title,
        requirement,
        false,
        priority,
        selectedTags,
      )

      if (!created) {
        setTaskCreator(prev =>
          prev
            ? {
                ...prev,
                isCreating: false,
                error: '任务节点无法放置，请先整理画布后重试。',
              }
            : prev,
        )
        return
      }

      const targetSpace =
        spacesRef.current.find(space => {
          if (!space.rect) {
            return false
          }

          return (
            taskCreator.anchor.x >= space.rect.x &&
            taskCreator.anchor.x <= space.rect.x + space.rect.width &&
            taskCreator.anchor.y >= space.rect.y &&
            taskCreator.anchor.y <= space.rect.y + space.rect.height
          )
        }) ?? null

      if (targetSpace) {
        const nextSpaces = sanitizeSpaces(
          spacesRef.current.map(space => {
            const filtered = space.nodeIds.filter(nodeId => nodeId !== created.id)

            if (space.id !== targetSpace.id) {
              return { ...space, nodeIds: filtered }
            }

            return { ...space, nodeIds: [...new Set([...filtered, created.id])] }
          }),
        )

        const { spaces: pushedSpaces, nodePositionById } = expandSpaceToFitOwnedNodesAndPushAway({
          targetSpaceId: targetSpace.id,
          spaces: nextSpaces,
          nodeRects: nodesRef.current.map(node => ({
            id: node.id,
            rect: {
              x: node.position.x,
              y: node.position.y,
              width: node.data.width,
              height: node.data.height,
            },
          })),
          gap: 24,
        })

        if (nodePositionById.size > 0) {
          setNodes(
            prevNodes => {
              let hasChanged = false
              const next = prevNodes.map(node => {
                const nextPosition = nodePositionById.get(node.id)
                if (!nextPosition) {
                  return node
                }

                if (node.position.x === nextPosition.x && node.position.y === nextPosition.y) {
                  return node
                }

                hasChanged = true
                return {
                  ...node,
                  position: nextPosition,
                }
              })

              return hasChanged ? next : prevNodes
            },
            { syncLayout: false },
          )
        }

        onSpacesChange(pushedSpaces)
        onRequestPersistFlush?.()
      }

      setTaskCreator(null)

      const shouldAutoFillTitle = titleInput.length === 0
      const shouldAutoFillPriority = priority === 'medium'
      const shouldAutoFillTags = selectedTags.length === 0

      const shouldAutoFill =
        taskCreator.autoGenerateTitle &&
        (shouldAutoFillTitle || shouldAutoFillPriority || shouldAutoFillTags)

      if (!shouldAutoFill || created.data.kind !== 'task' || !created.data.task) {
        return
      }

      const createdNodeId = created.id
      const createdTitleSnapshot = created.data.title
      const createdPrioritySnapshot = created.data.task.priority
      const createdTagsSnapshot = created.data.task.tags

      setNodes(
        prevNodes =>
          prevNodes.map(node => {
            if (node.id !== createdNodeId || node.data.kind !== 'task' || !node.data.task) {
              return node
            }

            if (node.data.task.isEnriching === true) {
              return node
            }

            return {
              ...node,
              data: {
                ...node.data,
                task: {
                  ...node.data.task,
                  isEnriching: true,
                },
              },
            }
          }),
        { syncLayout: false },
      )

      void (async () => {
        let suggestion: { title: string; priority: TaskPriority; tags: string[] } | null = null

        try {
          suggestion = await suggestTaskTitle(requirement)
        } catch {
          suggestion = null
        }

        const now = new Date().toISOString()

        let shouldPersist = false

        setNodes(
          prevNodes => {
            let hasChanged = false

            const nextNodes = prevNodes.map(node => {
              if (node.id !== createdNodeId || node.data.kind !== 'task' || !node.data.task) {
                return node
              }

              const shouldUpdateEnriching = node.data.task.isEnriching === true
              let nextTitle = node.data.title
              let nextPriority = node.data.task.priority
              let nextTags = node.data.task.tags
              let nextAutoGeneratedTitle = node.data.task.autoGeneratedTitle
              let didEnrichContent = false

              if (suggestion) {
                nextTitle =
                  shouldAutoFillTitle && node.data.title === createdTitleSnapshot
                    ? suggestion.title
                    : node.data.title
                nextPriority =
                  shouldAutoFillPriority && node.data.task.priority === createdPrioritySnapshot
                    ? suggestion.priority
                    : node.data.task.priority
                const tagsMatchSnapshot =
                  node.data.task.tags.length === createdTagsSnapshot.length &&
                  node.data.task.tags.every((tag, index) => tag === createdTagsSnapshot[index])
                nextTags =
                  shouldAutoFillTags && tagsMatchSnapshot ? suggestion.tags : node.data.task.tags

                nextAutoGeneratedTitle =
                  shouldAutoFillTitle && node.data.title === createdTitleSnapshot
                    ? true
                    : node.data.task.autoGeneratedTitle

                didEnrichContent =
                  nextTitle !== node.data.title ||
                  nextPriority !== node.data.task.priority ||
                  nextTags !== node.data.task.tags ||
                  nextAutoGeneratedTitle !== node.data.task.autoGeneratedTitle
              }

              if (!shouldUpdateEnriching && !didEnrichContent) {
                return node
              }

              hasChanged = true

              if (didEnrichContent) {
                shouldPersist = true
              }

              return {
                ...node,
                data: {
                  ...node.data,
                  title: didEnrichContent ? nextTitle : node.data.title,
                  task: {
                    ...node.data.task,
                    isEnriching: false,
                    priority: didEnrichContent ? nextPriority : node.data.task.priority,
                    tags: didEnrichContent ? nextTags : node.data.task.tags,
                    autoGeneratedTitle: didEnrichContent
                      ? nextAutoGeneratedTitle
                      : node.data.task.autoGeneratedTitle,
                    updatedAt: didEnrichContent ? now : node.data.task.updatedAt,
                  },
                },
              }
            })

            return hasChanged ? nextNodes : prevNodes
          },
          { syncLayout: false },
        )

        if (shouldPersist) {
          onRequestPersistFlush?.()
        }
      })()
    } catch (error) {
      setTaskCreator(prev =>
        prev
          ? {
              ...prev,
              isCreating: false,
              error: `创建任务失败：${toErrorMessage(error)}`,
            }
          : prev,
      )
    }
  }, [
    createTaskNode,
    fallbackTaskTitle,
    nodesRef,
    onRequestPersistFlush,
    onSpacesChange,
    setNodes,
    spacesRef,
    suggestTaskTitle,
    taskCreator,
    taskTagOptions,
  ])

  return {
    taskCreator,
    setTaskCreator,
    openTaskCreator,
    closeTaskCreator,
    generateTaskTitle,
    createTask,
  }
}
