import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  launchApp,
  storageKey,
  testWorkspacePath,
} from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Spaces (Anchors & Mismatch)', () => {
  test('creates new tasks in the space under the cursor (right-click anchor)', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-anchor-placeholder',
            title: 'placeholder-task',
            position: { x: 420, y: 260 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'placeholder',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
        ],
        {
          spaces: [
            {
              id: 'space-anchor',
              name: 'Anchor Scope',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-anchor-placeholder'],
              rect: { x: 340, y: 200, width: 700, height: 520 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 380, y: 240 },
      })
      await window.locator('[data-testid="workspace-context-new-task"]').click()

      await expect(window.locator('[data-testid="workspace-task-creator"]')).toBeVisible()
      await window.locator('[data-testid="workspace-task-advanced-toggle"]').click()
      await window.locator('[data-testid="workspace-task-title"]').fill('Anchored Task')
      await window
        .locator('[data-testid="workspace-task-requirement"]')
        .fill('Created inside space anchor')
      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      await expect(window.locator('.task-node')).toHaveCount(2)

      const belongs = await window.evaluate(
        async ({ key, spaceId }) => {
          void key

          const raw = await window.coveApi.persistence.readWorkspaceStateRaw()
          if (!raw) {
            return null
          }

          const parsed = JSON.parse(raw) as {
            workspaces?: Array<{
              nodes?: Array<{ id?: string; kind?: string; task?: { requirement?: string } | null }>
              spaces?: Array<{ id?: string; nodeIds?: string[] }>
            }>
          }

          const workspace = parsed.workspaces?.[0]
          if (!workspace) {
            return null
          }

          const createdTask = (workspace.nodes ?? []).find(
            node =>
              node.kind === 'task' && node.task?.requirement === 'Created inside space anchor',
          )
          const space = (workspace.spaces ?? []).find(item => item.id === spaceId)

          return createdTask?.id && Array.isArray(space?.nodeIds)
            ? space?.nodeIds.includes(createdTask.id)
            : null
        },
        { key: storageKey, spaceId: 'space-anchor' },
      )

      expect(belongs).toBe(true)
    } finally {
      await electronApp.close()
    }
  })

  test('marks terminal/agent directory mismatch when moving into another directory space', async () => {
    const { electronApp, window } = await launchApp()

    try {
      const worktreePath = `${testWorkspacePath}/.cove/worktrees/wt-ownership`

      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-placeholder-task',
            title: 'task-in-space',
            position: { x: 720, y: 240 },
            width: 360,
            height: 220,
            kind: 'task',
            status: null,
            task: {
              requirement: 'placeholder',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'mismatch-agent',
            title: 'codex · gpt-5.2-codex',
            position: { x: 120, y: 120 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'running',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'dir mismatch test',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: null,
            },
          },
        ],
        {
          spaces: [
            {
              id: 'space-worktree',
              name: 'Worktree Scope',
              directoryPath: worktreePath,
              nodeIds: ['space-placeholder-task'],
              rect: { x: 680, y: 200, width: 520, height: 360 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      const agentNode = window
        .locator('.terminal-node')
        .filter({ hasText: 'codex · gpt-5.2-codex' })
        .first()
      await expect(agentNode).toBeVisible()
      await expect(agentNode.locator('.terminal-node__badge--warning')).toHaveCount(0)

      await agentNode.locator('.terminal-node__header').dragTo(pane, {
        sourcePosition: { x: 80, y: 16 },
        targetPosition: { x: 820, y: 320 },
      })

      await expect(agentNode.locator('.terminal-node__badge--warning')).toContainText(
        'DIR MISMATCH',
      )

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key, nodeId }) => {
              void key

              const raw = await window.coveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{
                    id?: string
                    agent?: {
                      expectedDirectory?: string | null
                    } | null
                  }>
                }>
              }

              const node = parsed.workspaces?.[0]?.nodes?.find(item => item.id === nodeId)
              return node?.agent?.expectedDirectory ?? null
            },
            { key: storageKey, nodeId: 'mismatch-agent' },
          )
        })
        .toBe(worktreePath)
    } finally {
      await electronApp.close()
    }
  })
})
