import { expect, test, type Locator, type Page } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  dragLocatorTo,
  launchApp,
  readLocatorClientRect,
  storageKey,
  testWorkspacePath,
} from './workspace-canvas.helpers'

const CONTEXT_MENU_TRIGGER_TIMEOUT_MS = 10_000
const CONTEXT_MENU_ITEM_VISIBLE_TIMEOUT_MS = 2_000
const CONTEXT_MENU_ITEM_CLICK_TIMEOUT_MS = 10_000

async function clickCreateSpaceFromSelectionContextMenu(
  window: Page,
  trigger: Locator,
  triggerPosition: { x: number; y: number },
  attempt = 0,
): Promise<void> {
  const createSpaceAction = window.locator('[data-testid="workspace-selection-create-space"]')

  await trigger.click({
    button: 'right',
    position: triggerPosition,
    timeout: CONTEXT_MENU_TRIGGER_TIMEOUT_MS,
  })

  try {
    await createSpaceAction.waitFor({
      state: 'visible',
      timeout: CONTEXT_MENU_ITEM_VISIBLE_TIMEOUT_MS,
    })
    await createSpaceAction.click({ timeout: CONTEXT_MENU_ITEM_CLICK_TIMEOUT_MS })
  } catch (error) {
    if (attempt >= 2) {
      throw error
    }

    await window.keyboard.press('Escape').catch(() => undefined)
    await clickCreateSpaceFromSelectionContextMenu(window, trigger, triggerPosition, attempt + 1)
  }
}

test.describe('Workspace Canvas - Spaces (Task Directory Guards)', () => {
  test('allows moving a task when its linked agent is inactive', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'inactive-task',
            title: 'movable-task',
            position: { x: 120, y: 120 },
            width: 420,
            height: 260,
            kind: 'task',
            status: null,
            task: {
              requirement: 'inactive agent task',
              status: 'todo',
              priority: 'medium',
              tags: [],
              linkedAgentNodeId: 'inactive-agent',
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'inactive-agent',
            title: 'codex · inactive',
            position: { x: 620, y: 120 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'exited',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: '2026-02-09T00:10:00.000Z',
            exitCode: 0,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'inactive',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: 'session-inactive',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: 'inactive-task',
            },
          },
        ],
        { activeSpaceId: null },
      )

      const taskNode = window.locator('.task-node').filter({ hasText: 'movable-task' }).first()
      await expect(taskNode).toBeVisible()

      const header = taskNode.locator('.task-node__header')
      const headerClickPosition = { x: 80, y: 18 }
      await header.click({
        position: headerClickPosition,
        timeout: CONTEXT_MENU_TRIGGER_TIMEOUT_MS,
      })
      await clickCreateSpaceFromSelectionContextMenu(window, header, headerClickPosition)

      await expect(window.locator('.workspace-space-region')).toHaveCount(1)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key, nodeId, agentNodeId }) => {
              void key

              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const spaces = parsed.workspaces?.[0]?.spaces ?? []
              const owningSpace = spaces.find(space => space.nodeIds?.includes(nodeId))

              return {
                spaceCount: spaces.length,
                taskOwned: Boolean(owningSpace),
                movedLinkedAgentWithTask: owningSpace?.nodeIds?.includes(agentNodeId) ?? false,
              }
            },
            { key: storageKey, nodeId: 'inactive-task', agentNodeId: 'inactive-agent' },
          )
        })
        .toEqual({
          spaceCount: 1,
          taskOwned: true,
          movedLinkedAgentWithTask: false,
        })
    } finally {
      await electronApp.close()
    }
  })

  test('prevents moving a task when its linked agent is active', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'active-task',
            title: 'blocked-task',
            position: { x: 120, y: 120 },
            width: 420,
            height: 260,
            kind: 'task',
            status: null,
            task: {
              requirement: 'active agent task',
              status: 'doing',
              priority: 'medium',
              tags: [],
              linkedAgentNodeId: 'active-agent',
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'active-agent',
            title: 'codex · active',
            position: { x: 620, y: 120 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'standby',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'active',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: 'session-active',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: 'active-task',
            },
          },
        ],
        { activeSpaceId: null },
      )

      const taskNode = window.locator('.task-node').filter({ hasText: 'blocked-task' }).first()
      await expect(taskNode).toBeVisible()

      const header = taskNode.locator('.task-node__header')
      const headerClickPosition = { x: 80, y: 18 }
      await header.click({
        position: headerClickPosition,
        timeout: CONTEXT_MENU_TRIGGER_TIMEOUT_MS,
      })
      await clickCreateSpaceFromSelectionContextMenu(window, header, headerClickPosition)

      await expect(window.locator('[data-testid="app-message"]')).toContainText(
        'Tasks with active agents cannot be moved between spaces.',
      )

      await expect(window.locator('.workspace-space-region')).toHaveCount(0)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key }) => {
              void key

              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{ id?: string; position?: { x?: number; y?: number } }>
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const workspace = parsed.workspaces?.[0]

              return {
                spaceCount: workspace?.spaces?.length ?? 0,
              }
            },
            { key: storageKey },
          )
        })
        .toEqual({
          spaceCount: 0,
        })
    } finally {
      await electronApp.close()
    }
  })

  test('allows moving a task with an active agent within the same space', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'active-space-task',
            title: 'space-task',
            position: { x: 220, y: 220 },
            width: 420,
            height: 260,
            kind: 'task',
            status: null,
            task: {
              requirement: 'active agent task in space',
              status: 'doing',
              priority: 'medium',
              tags: [],
              linkedAgentNodeId: 'active-space-agent',
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'active-space-agent',
            title: 'codex · active in space',
            position: { x: 720, y: 220 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'standby',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'active in space',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: 'session-active-space',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: 'active-space-task',
            },
          },
        ],
        {
          spaces: [
            {
              id: 'space-active-task',
              name: 'Active Task Space',
              directoryPath: testWorkspacePath,
              nodeIds: ['active-space-task'],
              rect: { x: 120, y: 140, width: 760, height: 540 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const spaceRegion = window.locator('.workspace-space-region').first()
      await expect(spaceRegion).toBeVisible()
      const spaceBox = await readLocatorClientRect(spaceRegion)

      const taskNode = window.locator('.task-node').filter({ hasText: 'space-task' }).first()
      await expect(taskNode).toBeVisible()

      await dragLocatorTo(window, taskNode.locator('.task-node__header'), spaceRegion, {
        sourcePosition: { x: 120, y: 16 },
        targetPosition: {
          x: Math.min(Math.max(420, Math.round(spaceBox.width * 0.72)), spaceBox.width - 80),
          y: Math.min(Math.max(260, Math.round(spaceBox.height * 0.62)), spaceBox.height - 60),
        },
        steps: 12,
      })

      await expect(window.locator('[data-testid="app-message"]')).toHaveCount(0)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key, nodeId, spaceId }) => {
              void key

              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{ id?: string; position?: { x?: number; y?: number } }>
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const workspace = parsed.workspaces?.[0]
              const persistedTaskNode = workspace?.nodes?.find(node => node.id === nodeId)
              const space = workspace?.spaces?.find(item => item.id === spaceId)

              return {
                moved:
                  typeof persistedTaskNode?.position?.x === 'number' &&
                  typeof persistedTaskNode?.position?.y === 'number' &&
                  (persistedTaskNode.position.x !== 220 || persistedTaskNode.position.y !== 220),
                belongsToSpace: space?.nodeIds?.includes(nodeId) ?? false,
              }
            },
            { key: storageKey, nodeId: 'active-space-task', spaceId: 'space-active-task' },
          )
        })
        .toEqual({
          moved: true,
          belongsToSpace: true,
        })
    } finally {
      await electronApp.close()
    }
  })
})
