import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  dragLocatorTo,
  launchApp,
  readCanvasViewport,
} from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Minimap & Zoom', () => {
  test('renders subdued canvas controls and collapsible minimap', async ({
    browserName,
  }, testInfo) => {
    const { electronApp, window } = await launchApp()

    try {
      void browserName
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'node-controls-minimap',
            title: 'terminal-controls-minimap',
            position: { x: 180, y: 140 },
            width: 460,
            height: 300,
            kind: 'terminal',
          },
          {
            id: 'note-minimap',
            title: 'note-minimap',
            position: { x: 760, y: 180 },
            width: 420,
            height: 280,
            kind: 'note',
            task: {
              text: 'Minimap should remain readable in light theme.',
            },
          },
          {
            id: 'task-minimap',
            title: 'task-minimap',
            position: { x: 1120, y: 520 },
            width: 460,
            height: 280,
            kind: 'task',
            task: {
              requirement: 'Minimap nodes should be visible without hover.',
              status: 'doing',
              priority: 'medium',
              tags: ['minimap'],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
          {
            id: 'terminal-minimap-2',
            title: 'terminal-minimap-2',
            position: { x: 420, y: 740 },
            width: 440,
            height: 260,
            kind: 'terminal',
          },
          {
            id: 'terminal-minimap-3',
            title: 'terminal-minimap-3',
            position: { x: 1400, y: 220 },
            width: 420,
            height: 260,
            kind: 'terminal',
          },
        ],
        {
          settings: { uiTheme: 'light' },
        },
      )

      await expect
        .poll(() =>
          window.evaluate(() => {
            return document.documentElement.dataset.coveTheme ?? null
          }),
        )
        .toBe('light')

      const controls = window.locator('.workspace-canvas__controls')
      await expect(controls).toBeVisible()

      const controlsOpacity = await controls.evaluate(element => {
        return Number.parseFloat(window.getComputedStyle(element).opacity)
      })
      expect(controlsOpacity).toBeLessThan(0.8)

      const minimapToggle = window.locator('[data-testid="workspace-minimap-toggle"]')
      const minimap = window.locator('.workspace-canvas__minimap')
      await expect(minimap).toBeVisible()

      const readMinimapOpacity = async (): Promise<number> => {
        return await minimap.evaluate(element => {
          return Number.parseFloat(window.getComputedStyle(element).opacity)
        })
      }

      const minimapOpacityIdle = await readMinimapOpacity()
      expect(minimapOpacityIdle).toBeGreaterThan(0.3)
      expect(minimapOpacityIdle).toBeLessThan(0.8)

      const parseAlpha = (color: string): number => {
        const rgbaMatch = color.match(/rgba\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*,\s*([0-9.]+)\s*\)/)
        if (rgbaMatch) {
          return Number.parseFloat(rgbaMatch[1])
        }
        if (color.startsWith('rgb(')) {
          return 1
        }
        return Number.NaN
      }

      const minimapBackgroundColor = await minimap.evaluate(element => {
        return window.getComputedStyle(element).backgroundColor
      })
      const minimapBackgroundAlpha = parseAlpha(minimapBackgroundColor)
      expect(minimapBackgroundAlpha).toBeGreaterThan(0.55)
      expect(minimapBackgroundAlpha).toBeLessThan(1)

      const minimapNode = window.locator('.react-flow__minimap-node').first()
      await expect(minimapNode).toBeVisible()
      const minimapNodeFill = await minimapNode.evaluate(element => {
        return window.getComputedStyle(element).fill
      })
      expect(minimapNodeFill).not.toBe('none')
      const minimapNodeAlpha = parseAlpha(minimapNodeFill)
      // Light theme minimap nodes should be visible but not overly saturated.
      expect(minimapNodeAlpha).toBeGreaterThan(0.45)
      expect(minimapNodeAlpha).toBeLessThan(0.85)

      const screenshotPath = testInfo.outputPath('minimap-light.png')
      await window.screenshot({ path: screenshotPath })
      await testInfo.attach('minimap-light', { path: screenshotPath, contentType: 'image/png' })

      await expect(minimapToggle).toHaveCSS('visibility', 'hidden')

      await window.locator('.workspace-canvas__minimap-dock').hover()
      await expect.poll(readMinimapOpacity).toBeGreaterThan(0.9)
      const minimapOpacityHover = await readMinimapOpacity()
      expect(minimapOpacityHover).toBeGreaterThan(minimapOpacityIdle + 0.2)

      const hoverScreenshotPath = testInfo.outputPath('minimap-light-hover.png')
      await window.screenshot({ path: hoverScreenshotPath })
      await testInfo.attach('minimap-light-hover', {
        path: hoverScreenshotPath,
        contentType: 'image/png',
      })

      await expect(minimapToggle).toBeVisible()
      await expect(minimapToggle).toHaveCSS('visibility', 'visible')
      await expect(minimapToggle).toHaveAttribute('aria-label', 'Hide minimap')

      await minimapToggle.click()
      await expect(minimap).toHaveCount(0)
      await expect(minimapToggle).toBeVisible()
      await expect(minimapToggle).toHaveCSS('visibility', 'visible')
      await expect(minimapToggle).toHaveAttribute('aria-label', 'Show minimap')

      await minimapToggle.click()
      await expect(minimap).toBeVisible()
      await window.locator('.workspace-canvas .react-flow__pane').hover()
      await expect(minimapToggle).toHaveCSS('visibility', 'hidden')
      await expect(minimapToggle).toHaveAttribute('aria-label', 'Hide minimap')
    } finally {
      await electronApp.close()
    }
  })

  test('dragging terminal header does not normalize canvas zoom', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-header-zoom',
          title: 'terminal-header-zoom',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
      ])

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()

      await zoomInButton.click()
      await zoomInButton.click()

      const zoomBefore = (await readCanvasViewport(window)).zoom
      expect(zoomBefore).toBeGreaterThan(1.01)

      const terminal = window.locator('.terminal-node').first()
      await expect(terminal).toBeVisible()

      const header = terminal.locator('.terminal-node__header')
      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await dragLocatorTo(window, header, pane, {
        sourcePosition: { x: 120, y: 16 },
        targetPosition: { x: 680, y: 420 },
      })

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeGreaterThan(1.01)

      await expect(window.locator('.react-flow__node.dragging')).toHaveCount(0)

      const terminalBody = terminal.locator('.terminal-node__terminal')
      const terminalBox = await terminalBody.boundingBox()
      if (!terminalBox) {
        throw new Error('terminal bounding box unavailable for normalization click')
      }

      // Click near the center of the terminal to avoid occluded edges after drag while zoomed-in.
      await window.mouse.click(
        terminalBox.x + terminalBox.width / 2,
        terminalBox.y + Math.min(96, terminalBox.height / 2),
      )

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeCloseTo(1, 2)
    } finally {
      await electronApp.close()
    }
  })

  test('normalizes canvas zoom and centers clicked terminal', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-zoom-1',
          title: 'terminal-zoom-1',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
        {
          id: 'node-zoom-2',
          title: 'terminal-zoom-2',
          position: { x: 700, y: 440 },
          width: 460,
          height: 300,
        },
      ])

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()

      await zoomInButton.click()
      await zoomInButton.click()

      const zoomBefore = (await readCanvasViewport(window)).zoom
      expect(zoomBefore).toBeGreaterThan(1.01)

      const secondTerminal = window.locator('.terminal-node').filter({ hasText: 'terminal-zoom-2' })
      await expect(secondTerminal).toBeVisible()

      const readCenterDelta = async (): Promise<{ dx: number; dy: number }> => {
        const canvasBox = await window.locator('.workspace-canvas .react-flow').boundingBox()
        const terminalBox = await secondTerminal.boundingBox()

        if (!canvasBox || !terminalBox) {
          return {
            dx: Number.POSITIVE_INFINITY,
            dy: Number.POSITIVE_INFINITY,
          }
        }

        const canvasCenterX = canvasBox.x + canvasBox.width / 2
        const canvasCenterY = canvasBox.y + canvasBox.height / 2
        const terminalCenterX = terminalBox.x + terminalBox.width / 2
        const terminalCenterY = terminalBox.y + terminalBox.height / 2

        return {
          dx: Math.abs(canvasCenterX - terminalCenterX),
          dy: Math.abs(canvasCenterY - terminalCenterY),
        }
      }

      const deltaBefore = await readCenterDelta()
      expect(deltaBefore.dx).toBeGreaterThan(120)

      const terminalBody = secondTerminal.locator('.terminal-node__terminal')
      await expect(terminalBody).toBeVisible()
      // Click further inside the terminal surface to avoid edge resize handles after zoom.
      const safeOffsetX = Math.ceil(16 + zoomBefore * 10)
      await terminalBody.click({ position: { x: safeOffsetX, y: 24 } })

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeCloseTo(1, 2)

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dx
        })
        .toBeLessThan(140)

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dy
        })
        .toBeLessThan(140)
    } finally {
      await electronApp.close()
    }
  })

  test('normalizes canvas zoom for clicked task but not header drag', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'task-click-focus',
          title: 'Focus task viewport',
          position: { x: 640, y: 420 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Clicking this task should center the viewport.',
            status: 'doing',
            priority: 'medium',
            tags: ['focus'],
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
          },
        },
      ])

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()

      await zoomInButton.click()
      await zoomInButton.click()

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeGreaterThan(1.01)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await dragLocatorTo(window, taskNode.locator('.task-node__header'), pane, {
        sourcePosition: { x: 120, y: 18 },
        targetPosition: { x: 240, y: 220 },
      })

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeGreaterThan(1.01)

      await taskNode.locator('.task-node__requirement-input').click({
        position: { x: 48, y: 36 },
      })

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeCloseTo(1, 2)

      const readCenterDelta = async (): Promise<{ dx: number; dy: number }> => {
        const canvasBox = await window.locator('.workspace-canvas .react-flow').boundingBox()
        const taskBox = await taskNode.boundingBox()

        if (!canvasBox || !taskBox) {
          return {
            dx: Number.POSITIVE_INFINITY,
            dy: Number.POSITIVE_INFINITY,
          }
        }

        const canvasCenterX = canvasBox.x + canvasBox.width / 2
        const canvasCenterY = canvasBox.y + canvasBox.height / 2
        const taskCenterX = taskBox.x + taskBox.width / 2
        const taskCenterY = taskBox.y + taskBox.height / 2

        return {
          dx: Math.abs(canvasCenterX - taskCenterX),
          dy: Math.abs(canvasCenterY - taskCenterY),
        }
      }

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dx
        })
        .toBeLessThan(140)

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dy
        })
        .toBeLessThan(140)
    } finally {
      await electronApp.close()
    }
  })
})
