import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  launchApp,
  storageKey,
  testWorkspacePath,
} from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Spaces (Auto Resize on Create)', () => {
  test('keeps crowded space members non-overlapping and enclosed after creation', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-crowded-left',
            title: 'crowded-left',
            position: { x: 240, y: 260 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'left',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'space-crowded-right',
            title: 'crowded-right',
            position: { x: 720, y: 260 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'right',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'root-near-space',
            title: 'root-near-space',
            position: { x: 1240, y: 260 },
            width: 460,
            height: 300,
            kind: 'terminal',
            status: null,
            startedAt: null,
            endedAt: null,
            exitCode: null,
            lastError: null,
            scrollback: null,
            executionDirectory: testWorkspacePath,
            expectedDirectory: testWorkspacePath,
            agent: null,
            task: null,
          },
        ],
        {
          spaces: [
            {
              id: 'space-crowded',
              name: 'Crowded Space',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-crowded-left', 'space-crowded-right'],
              rect: { x: 200, y: 220, width: 1020, height: 420 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 210, y: 280 },
      })
      await window.locator('[data-testid="workspace-context-new-task"]').click()

      await expect(window.locator('[data-testid="workspace-task-creator"]')).toBeVisible()
      await window.locator('[data-testid="workspace-task-advanced-toggle"]').click()
      await window.locator('[data-testid="workspace-task-title"]').fill('Crowded Task')
      await window.locator('[data-testid="workspace-task-requirement"]').fill('created-in-crowded')
      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      await expect(window.locator('.task-node')).toHaveCount(3)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key }) => {
              void key

              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{
                    id?: string
                    kind?: string
                    position?: { x?: number; y?: number }
                    width?: number
                    height?: number
                    task?: { requirement?: string } | null
                  }>
                  spaces?: Array<{
                    id?: string
                    rect?: { x?: number; y?: number; width?: number; height?: number } | null
                    nodeIds?: string[]
                  }>
                }>
              }

              const workspace = parsed.workspaces?.[0]
              if (!workspace) {
                return null
              }

              const space = (workspace.spaces ?? []).find(item => item.id === 'space-crowded')
              if (!space?.rect || !Array.isArray(space.nodeIds)) {
                return null
              }

              const rect = space.rect
              if (
                typeof rect.x !== 'number' ||
                typeof rect.y !== 'number' ||
                typeof rect.width !== 'number' ||
                typeof rect.height !== 'number'
              ) {
                return null
              }

              const nodeById = new Map((workspace.nodes ?? []).map(node => [node.id ?? '', node]))
              const memberRects = space.nodeIds
                .map(nodeId => {
                  const node = nodeById.get(nodeId)
                  if (
                    !node?.position ||
                    typeof node.position.x !== 'number' ||
                    typeof node.position.y !== 'number' ||
                    typeof node.width !== 'number' ||
                    typeof node.height !== 'number'
                  ) {
                    return null
                  }

                  return {
                    id: nodeId,
                    left: node.position.x,
                    top: node.position.y,
                    right: node.position.x + node.width,
                    bottom: node.position.y + node.height,
                  }
                })
                .filter(
                  (
                    item,
                  ): item is {
                    id: string
                    left: number
                    top: number
                    right: number
                    bottom: number
                  } => Boolean(item),
                )

              const membersInside = space.nodeIds.every(nodeId => {
                const memberRect = memberRects.find(item => item.id === nodeId)
                if (!memberRect) {
                  return false
                }

                const spaceRight = rect.x + rect.width
                const spaceBottom = rect.y + rect.height

                return (
                  memberRect.left >= rect.x &&
                  memberRect.top >= rect.y &&
                  memberRect.right <= spaceRight &&
                  memberRect.bottom <= spaceBottom
                )
              })

              const membersOverlap = memberRects.some((leftRect, leftIndex) =>
                memberRects.some((rightRect, rightIndex) => {
                  if (rightIndex <= leftIndex) {
                    return false
                  }

                  return !(
                    leftRect.right <= rightRect.left ||
                    leftRect.left >= rightRect.right ||
                    leftRect.bottom <= rightRect.top ||
                    leftRect.top >= rightRect.bottom
                  )
                }),
              )

              const root = nodeById.get('root-near-space')
              const rootClear =
                !root?.position ||
                typeof root.position.x !== 'number' ||
                typeof root.position.y !== 'number' ||
                typeof root.width !== 'number' ||
                typeof root.height !== 'number'
                  ? false
                  : (() => {
                      const rootLeft = root.position.x
                      const rootTop = root.position.y
                      const rootRight = root.position.x + root.width
                      const rootBottom = root.position.y + root.height
                      const spaceRight = rect.x + rect.width
                      const spaceBottom = rect.y + rect.height

                      return (
                        rootRight <= rect.x ||
                        rootLeft >= spaceRight ||
                        rootBottom <= rect.y ||
                        rootTop >= spaceBottom
                      )
                    })()

              return { membersInside, membersOverlap, rootClear }
            },
            { key: storageKey },
          )
        })
        .toEqual({ membersInside: true, membersOverlap: false, rootClear: true })
    } finally {
      await electronApp.close()
    }
  })
})
