import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, testWorkspacePath } from './workspace-canvas.helpers'
import {
  clickPaneAtFlowPoint,
  ensureArtifactsDir,
  openPaneContextMenuAtFlowPoint,
  rectsOverlap,
  readSeededWorkspaceLayout,
} from './workspace-canvas.arrange.shared'

test.describe('Workspace Canvas - Arrange Semantics', () => {
  test('places ideas first, then task-linked agent, then the remaining canvas content', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'note-lane',
          title: 'Idea',
          position: { x: 0, y: 0 },
          width: 320,
          height: 220,
          kind: 'note',
          task: {
            text: 'Keep the note in the idea lane.',
          },
        },
        {
          id: 'task-lane',
          title: 'Plan',
          position: { x: 0, y: 0 },
          width: 420,
          height: 300,
          kind: 'task',
          status: null,
          task: {
            requirement: 'Plan',
            status: 'todo',
            priority: 'medium',
            tags: [],
            linkedAgentNodeId: 'agent-lane',
            agentSessions: [],
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: '2026-02-09T00:00:00.000Z',
            updatedAt: '2026-02-09T00:00:00.000Z',
          },
        },
        {
          id: 'agent-lane',
          title: 'Execute',
          position: { x: 0, y: 0 },
          width: 560,
          height: 720,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-09T00:05:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          agent: {
            provider: 'codex',
            prompt: 'Execute the planned task.',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'resume',
            resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
            resumeSessionIdVerified: true,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
        {
          id: 'terminal-lane',
          title: 'Terminal',
          position: { x: 0, y: 0 },
          width: 470,
          height: 650,
          kind: 'terminal',
        },
      ])

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await openPaneContextMenuAtFlowPoint(window, pane, { x: 900, y: 720 })
      await expect(window.locator('.workspace-context-menu')).toBeVisible()
      await window.locator('[data-testid="workspace-context-arrange-by"]').click()
      await expect(
        window.locator('[data-testid="workspace-context-arrange-by-menu"]'),
      ).toBeVisible()

      await window.locator('[data-testid="workspace-context-arrange-order-created"]').click()

      let layout: Awaited<ReturnType<typeof readSeededWorkspaceLayout>> | null = null
      await expect
        .poll(async () => {
          layout = await readSeededWorkspaceLayout(window, {
            nodeIds: ['note-lane', 'task-lane', 'agent-lane', 'terminal-lane'],
            spaceIds: [],
          })

          const note = layout.nodes['note-lane']
          const task = layout.nodes['task-lane']
          const agent = layout.nodes['agent-lane']
          const terminal = layout.nodes['terminal-lane']
          if (!note || !task || !agent || !terminal) {
            return false
          }

          return (
            note.x < task.x &&
            agent.x === task.x + 240 &&
            agent.y === task.y &&
            note.y === task.y &&
            task.y < terminal.y &&
            terminal.x === note.x
          )
        })
        .toBe(true)

      if (!layout) {
        throw new Error('Semantic arrange layout not available')
      }

      const note = layout.nodes['note-lane']!
      const task = layout.nodes['task-lane']!
      const agent = layout.nodes['agent-lane']!
      const terminal = layout.nodes['terminal-lane']!

      expect(note).toMatchObject({ width: 228, height: 156 })
      expect(task).toMatchObject({ width: 228, height: 324 })
      expect(agent).toMatchObject({ width: 468, height: 660 })
      expect(terminal).toMatchObject({ width: 468, height: 324 })

      expect(note.x).toBeLessThan(task.x)
      expect(note.y).toBe(task.y)
      expect(agent.x).toBe(task.x + 240)
      expect(agent.y).toBe(task.y)
      expect(terminal.x).toBe(note.x)
      expect(terminal.y).toBeGreaterThan(task.y)
      expect(rectsOverlap(task, agent)).toBe(false)
      expect(rectsOverlap(task, note)).toBe(false)
      expect(rectsOverlap(task, terminal)).toBe(false)
      expect(rectsOverlap(agent, note)).toBe(false)
      expect(rectsOverlap(agent, terminal)).toBe(false)
      expect(rectsOverlap(note, terminal)).toBe(false)

      await ensureArtifactsDir()
      await clickPaneAtFlowPoint(window, pane, { x: 960, y: 760 })
      await expect(window.locator('.workspace-context-menu')).toHaveCount(0)
      await window.screenshot({
        path: 'artifacts/workspace-canvas-arrange.semantic-task-agent-pair.png',
      })
    } finally {
      await electronApp.close()
    }
  })
})
