import { expect, type Page } from '@playwright/test'
import path from 'path'
import { createTestUserDataDir, launchApp } from './workspace-canvas.app'
import {
  buildEchoSequenceCommand,
  buildNodeEvalCommand,
  buildPaddedNumberSequenceCommand,
  removePathWithRetry,
} from './workspace-canvas.testUtils'

export const testWorkspacePath = path.resolve(__dirname, '../../')
export const storageKey = 'cove:m0:workspace-state'
export const seededWorkspaceId = 'workspace-seeded'
export { beginDragMouse, dragLocatorTo, dragMouse } from './workspace-canvas.gestures'
export {
  buildEchoSequenceCommand,
  buildNodeEvalCommand,
  buildPaddedNumberSequenceCommand,
  createTestUserDataDir,
  launchApp,
  removePathWithRetry,
}

export interface SeedAgentData {
  provider: 'claude-code' | 'codex' | 'opencode' | 'gemini'
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: 'new' | 'resume'
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
  executionDirectory: string
  expectedDirectory?: string | null
  directoryMode: 'workspace' | 'custom'
  customDirectory: string | null
  shouldCreateDirectory: boolean
}

export interface SeedTaskData {
  requirement: string
  status: 'todo' | 'doing' | 'ai_done' | 'done'
  priority?: 'low' | 'medium' | 'high' | 'urgent'
  tags?: string[]
  linkedAgentNodeId: string | null
  lastRunAt: string | null
  autoGeneratedTitle: boolean
  createdAt?: string | null
  updatedAt?: string | null
}

export type SeedNoteData = { text: string }

export interface SeedNode {
  id: string
  title: string
  position: { x: number; y: number }
  width: number
  height: number
  kind?: 'terminal' | 'agent' | 'task' | 'note'
  status?: 'running' | 'standby' | 'exited' | 'failed' | 'stopped' | 'restoring' | null
  startedAt?: string | null
  endedAt?: string | null
  exitCode?: number | null
  lastError?: string | null
  scrollback?: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent?: SeedAgentData | null
  task?: SeedTaskData | SeedNoteData | null
}

export interface SeedWorkspace {
  id: string
  name: string
  path: string
  nodes: SeedNode[]
  spaces?: Array<{
    id: string
    name: string
    directoryPath: string
    nodeIds: string[]
    rect?: {
      x: number
      y: number
      width: number
      height: number
    } | null
  }>
  activeSpaceId?: string | null
}

export async function seedWorkspaceState(
  window: Page,
  payload: {
    activeWorkspaceId: string
    workspaces: SeedWorkspace[]
    settings?: unknown
  },
): Promise<void> {
  const seededState = {
    formatVersion: 1,
    activeWorkspaceId: payload.activeWorkspaceId,
    workspaces: payload.workspaces,
    ...(payload.settings ? { settings: payload.settings } : {}),
  }

  const trySeed = async (attempt: number): Promise<boolean> => {
    if (attempt >= 3) {
      return false
    }

    const writeResult = await window.evaluate(async state => {
      return await window.opencoveApi.persistence.writeWorkspaceStateRaw({
        raw: JSON.stringify(state),
      })
    }, seededState)

    if (!writeResult.ok) {
      throw new Error(
        `Failed to seed workspace state: ${writeResult.reason}: ${writeResult.error.code}${
          writeResult.error.debugMessage ? `: ${writeResult.error.debugMessage}` : ''
        }`,
      )
    }

    await window.reload({ waitUntil: 'domcontentloaded' })

    const expectedWorkspaces = payload.workspaces.map(workspace => ({
      id: workspace.id,
      nodeIds: workspace.nodes.map(node => node.id),
    }))

    const seededReady = await window.evaluate(async workspaceExpectations => {
      const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
      if (!raw) {
        return false
      }

      try {
        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            id?: string
            nodes?: Array<{
              id?: string
            }>
          }>
        }

        if (!Array.isArray(parsed.workspaces)) {
          return false
        }

        const workspaceById = new Map(
          parsed.workspaces
            .filter(workspace => typeof workspace.id === 'string')
            .map(workspace => [workspace.id as string, workspace]),
        )

        return workspaceExpectations.every(expectedWorkspace => {
          const loadedWorkspace = workspaceById.get(expectedWorkspace.id)
          if (!loadedWorkspace || !Array.isArray(loadedWorkspace.nodes)) {
            return false
          }

          const loadedNodeIds = loadedWorkspace.nodes
            .map(node => (typeof node.id === 'string' ? node.id : ''))
            .filter(id => id.length > 0)

          if (loadedNodeIds.length !== expectedWorkspace.nodeIds.length) {
            return false
          }

          return expectedWorkspace.nodeIds.every(nodeId => loadedNodeIds.includes(nodeId))
        })
      } catch {
        return false
      }
    }, expectedWorkspaces)

    const workspaceCount = await window.locator('.workspace-item').count()
    if (seededReady && workspaceCount >= payload.workspaces.length) {
      return true
    }

    return await trySeed(attempt + 1)
  }

  const success = await trySeed(0)
  if (!success) {
    throw new Error('Failed to deterministically seed workspace state')
  }
}

export async function clearAndSeedWorkspace(
  window: Page,
  nodes: SeedNode[],
  options?: {
    settings?: unknown
    spaces?: SeedWorkspace['spaces']
    activeSpaceId?: string | null
  },
): Promise<void> {
  await seedWorkspaceState(window, {
    activeWorkspaceId: seededWorkspaceId,
    workspaces: [
      {
        id: seededWorkspaceId,
        name: path.basename(testWorkspacePath),
        path: testWorkspacePath,
        nodes,
        ...(options?.spaces ? { spaces: options.spaces } : {}),
        ...(options && 'activeSpaceId' in options ? { activeSpaceId: options.activeSpaceId } : {}),
      },
    ],
    settings: options?.settings,
  })
}

export async function readCanvasViewport(
  window: Page,
): Promise<{ x: number; y: number; zoom: number }> {
  return await window.evaluate(() => {
    const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null
    if (!viewport) {
      return { x: 0, y: 0, zoom: 1 }
    }

    const style = window.getComputedStyle(viewport)
    const transform = style.transform

    const matrixMatch = transform.match(/matrix\(([^)]+)\)/)
    if (matrixMatch) {
      const values = matrixMatch[1].split(',').map(item => Number(item.trim()))
      if (values.length < 6) {
        return { x: 0, y: 0, zoom: 1 }
      }

      const zoom = Number.isFinite(values[0]) ? values[0] : 1
      const x = Number.isFinite(values[4]) ? values[4] : 0
      const y = Number.isFinite(values[5]) ? values[5] : 0

      return { x, y, zoom }
    }

    const matrix3dMatch = transform.match(/matrix3d\(([^)]+)\)/)
    if (!matrix3dMatch) {
      return { x: 0, y: 0, zoom: 1 }
    }

    const values = matrix3dMatch[1].split(',').map(item => Number(item.trim()))
    if (values.length < 16) {
      return { x: 0, y: 0, zoom: 1 }
    }

    const zoom = Number.isFinite(values[0]) ? values[0] : 1
    const x = Number.isFinite(values[12]) ? values[12] : 0
    const y = Number.isFinite(values[13]) ? values[13] : 0

    return { x, y, zoom }
  })
}

export async function selectCoveOption(
  window: Page,
  testId: string,
  optionValue: string,
): Promise<void> {
  const trigger = window.locator(`[data-testid="${testId}-trigger"]`)
  await expect(trigger).toBeVisible()
  await trigger.click()

  const menu = window.locator(`[data-testid="${testId}-menu"]`)
  await expect(menu).toBeVisible()
  await menu
    .locator(`[data-cove-select-option-value="${optionValue.replaceAll('"', '\\"')}"]`)
    .click()
}
