import {
  expect,
  test,
  _electron as electron,
  type ElectronApplication,
  type Page,
} from '@playwright/test'
import path from 'path'

const electronAppPath = path.resolve(__dirname, '../../')
const testWorkspacePath = path.resolve(__dirname, '../../')
const storageKey = 'cove:m0:workspace-state'
const seededWorkspaceId = 'workspace-seeded'

interface SeedAgentData {
  provider: 'claude-code' | 'codex'
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: 'new' | 'resume'
  resumeSessionId: string | null
  executionDirectory: string
  directoryMode: 'workspace' | 'custom'
  customDirectory: string | null
  shouldCreateDirectory: boolean
}

interface SeedTaskData {
  requirement: string
  status: 'todo' | 'doing' | 'ai_done' | 'done'
  priority?: 'low' | 'medium' | 'high' | 'urgent'
  tags?: string[]
  linkedAgentNodeId: string | null
  lastRunAt: string | null
  autoGeneratedTitle: boolean
  createdAt?: string | null
  updatedAt?: string | null
}

interface SeedNode {
  id: string
  title: string
  position: {
    x: number
    y: number
  }
  width: number
  height: number
  kind?: 'terminal' | 'agent' | 'task'
  status?: 'running' | 'exited' | 'failed' | 'stopped' | 'restoring' | null
  startedAt?: string | null
  endedAt?: string | null
  exitCode?: number | null
  lastError?: string | null
  scrollback?: string | null
  agent?: SeedAgentData | null
  task?: SeedTaskData | null
}

interface SeedWorkspace {
  id: string
  name: string
  path: string
  nodes: SeedNode[]
  spaces?: Array<{
    id: string
    name: string
    directoryPath: string
    nodeIds: string[]
    rect?: {
      x: number
      y: number
      width: number
      height: number
    } | null
  }>
  activeSpaceId?: string | null
}

async function launchApp(): Promise<{ electronApp: ElectronApplication; window: Page }> {
  const electronApp = await electron.launch({
    args: [electronAppPath],
    env: {
      ...process.env,
      NODE_ENV: 'test',
      COVE_TEST_WORKSPACE: testWorkspacePath,
    },
  })

  const window = await electronApp.firstWindow()
  await window.waitForLoadState('domcontentloaded')

  return { electronApp, window }
}

async function seedWorkspaceState(
  window: Page,
  payload: {
    activeWorkspaceId: string
    workspaces: SeedWorkspace[]
    settings?: unknown
  },
): Promise<void> {
  const seededState = {
    activeWorkspaceId: payload.activeWorkspaceId,
    workspaces: payload.workspaces,
    ...(payload.settings ? { settings: payload.settings } : {}),
  }

  const trySeed = async (attempt: number): Promise<boolean> => {
    if (attempt >= 3) {
      return false
    }

    await window.evaluate(
      ({ key, state }) => {
        window.localStorage.setItem(key, JSON.stringify(state))
      },
      {
        key: storageKey,
        state: seededState,
      },
    )

    await window.reload({ waitUntil: 'domcontentloaded' })

    const seededReady = await window.evaluate(
      ({ key, expectedWorkspaces }) => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return false
        }

        try {
          const parsed = JSON.parse(raw) as {
            workspaces?: Array<{
              id?: string
              nodes?: Array<{
                id?: string
              }>
            }>
          }

          if (!Array.isArray(parsed.workspaces)) {
            return false
          }

          const workspaceById = new Map(
            parsed.workspaces
              .filter(workspace => typeof workspace.id === 'string')
              .map(workspace => [workspace.id as string, workspace]),
          )

          return expectedWorkspaces.every(expectedWorkspace => {
            const loadedWorkspace = workspaceById.get(expectedWorkspace.id)
            if (!loadedWorkspace || !Array.isArray(loadedWorkspace.nodes)) {
              return false
            }

            const loadedNodeIds = loadedWorkspace.nodes
              .map(node => (typeof node.id === 'string' ? node.id : ''))
              .filter(id => id.length > 0)

            if (loadedNodeIds.length !== expectedWorkspace.nodeIds.length) {
              return false
            }

            return expectedWorkspace.nodeIds.every(nodeId => loadedNodeIds.includes(nodeId))
          })
        } catch {
          return false
        }
      },
      {
        key: storageKey,
        expectedWorkspaces: payload.workspaces.map(workspace => ({
          id: workspace.id,
          nodeIds: workspace.nodes.map(node => node.id),
        })),
      },
    )

    const workspaceCount = await window.locator('.workspace-item').count()
    if (seededReady && workspaceCount >= payload.workspaces.length) {
      return true
    }

    return await trySeed(attempt + 1)
  }

  const success = await trySeed(0)
  if (!success) {
    throw new Error('Failed to deterministically seed workspace state')
  }
}

async function clearAndSeedWorkspace(
  window: Page,
  nodes: SeedNode[],
  options?: {
    settings?: unknown
    spaces?: SeedWorkspace['spaces']
    activeSpaceId?: string | null
  },
): Promise<void> {
  await seedWorkspaceState(window, {
    activeWorkspaceId: seededWorkspaceId,
    workspaces: [
      {
        id: seededWorkspaceId,
        name: path.basename(testWorkspacePath),
        path: testWorkspacePath,
        nodes,
        ...(options?.spaces ? { spaces: options.spaces } : {}),
        ...(options && 'activeSpaceId' in options ? { activeSpaceId: options.activeSpaceId } : {}),
      },
    ],
    settings: options?.settings,
  })
}

async function readCanvasViewport(window: Page): Promise<{ x: number; y: number; zoom: number }> {
  return await window.evaluate(() => {
    const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null
    if (!viewport) {
      return { x: 0, y: 0, zoom: 1 }
    }

    const style = window.getComputedStyle(viewport)
    const matrix = style.transform.match(/matrix\(([^)]+)\)/)
    if (!matrix) {
      return { x: 0, y: 0, zoom: 1 }
    }

    const values = matrix[1].split(',').map(item => Number(item.trim()))
    if (values.length < 6) {
      return { x: 0, y: 0, zoom: 1 }
    }

    const zoom = Number.isFinite(values[0]) ? values[0] : 1
    const x = Number.isFinite(values[4]) ? values[4] : 0
    const y = Number.isFinite(values[5]) ? values[5] : 0

    return { x, y, zoom }
  })
}

test.describe('Workspace Canvas Interactions', () => {
  test('keeps terminal visible after drag, resize, and node interactions', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-1',
          title: 'terminal-1',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
        {
          id: 'node-2',
          title: 'terminal-2',
          position: { x: 760, y: 200 },
          width: 460,
          height: 300,
        },
      ])

      await expect(window.locator('.workspace-canvas')).toBeVisible()
      await expect(window.locator('.workspace-item__meta').first()).toContainText('2 terminals')

      const terminals = window.locator('.terminal-node')
      await expect(terminals).toHaveCount(2)

      const firstTerminal = terminals.first()
      await expect(firstTerminal).toBeVisible()
      await expect(firstTerminal.locator('.xterm')).toBeVisible()

      const header = firstTerminal.locator('.terminal-node__header')
      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await header.dragTo(pane, {
        sourcePosition: { x: 80, y: 16 },
        targetPosition: { x: 520, y: 420 },
      })

      await expect(firstTerminal).toBeVisible()
      await expect(firstTerminal.locator('.xterm')).toBeVisible()

      const rightResizer = firstTerminal.locator('[data-testid="terminal-resizer-right"]')
      const rightResizerBox = await rightResizer.boundingBox()
      if (!rightResizerBox) {
        throw new Error('terminal right resizer bounding box unavailable')
      }

      const rightStartX = rightResizerBox.x + rightResizerBox.width / 2
      const rightStartY = rightResizerBox.y + rightResizerBox.height / 2

      await window.mouse.move(rightStartX, rightStartY)
      await window.mouse.down()
      await window.mouse.move(rightStartX + 120, rightStartY + 80)
      await window.mouse.up()

      const widthResizedNode = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return null
        }

        const state = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id: string
              width: number
              height: number
            }>
          }>
        }

        return state.workspaces?.[0]?.nodes?.find(node => node.id === 'node-1') ?? null
      }, storageKey)

      expect(widthResizedNode).toBeTruthy()
      expect(widthResizedNode?.width ?? 0).toBeGreaterThan(460)
      expect(widthResizedNode?.height).toBe(300)

      const bottomResizer = firstTerminal.locator('[data-testid="terminal-resizer-bottom"]')
      const bottomResizerBox = await bottomResizer.boundingBox()
      if (!bottomResizerBox) {
        throw new Error('terminal bottom resizer bounding box unavailable')
      }

      const bottomStartX = bottomResizerBox.x + bottomResizerBox.width / 2
      const bottomStartY = bottomResizerBox.y + bottomResizerBox.height / 2

      await window.mouse.move(bottomStartX, bottomStartY)
      await window.mouse.down()
      await window.mouse.move(bottomStartX + 120, bottomStartY + 80)
      await window.mouse.up()

      const heightResizedNode = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return null
        }

        const state = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id: string
              width: number
              height: number
            }>
          }>
        }

        return state.workspaces?.[0]?.nodes?.find(node => node.id === 'node-1') ?? null
      }, storageKey)

      expect(heightResizedNode).toBeTruthy()
      expect(heightResizedNode?.width).toBe(widthResizedNode?.width)
      expect(heightResizedNode?.height ?? 0).toBeGreaterThan(300)
      await expect(firstTerminal.locator('.xterm')).toBeVisible()

      await terminals.nth(1).locator('.terminal-node__header').click()

      await expect(firstTerminal).toBeVisible()
      await expect(firstTerminal.locator('.xterm')).toBeVisible()
    } finally {
      await electronApp.close()
    }
  })

  test('keeps agent tui visible while dragging window', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-agent-drag',
          title: 'codex · gpt-5.2-codex',
          position: { x: 120, y: 120 },
          width: 520,
          height: 320,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-09T00:00:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          agent: {
            provider: 'codex',
            prompt: 'Keep tui stable during drag',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'resume',
            resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
      ])

      const agentNode = window.locator('.terminal-node').first()
      await expect(agentNode).toBeVisible()
      await expect(agentNode.locator('.xterm')).toBeVisible()
      await expect(agentNode).toContainText('[cove-test-agent]')

      const header = agentNode.locator('.terminal-node__header')
      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await header.dragTo(pane, {
        sourcePosition: { x: 120, y: 16 },
        targetPosition: { x: 680, y: 420 },
      })

      await expect(agentNode).toBeVisible()
      await expect(agentNode.locator('.xterm')).toBeVisible()
      await expect(agentNode).toContainText('[cove-test-agent]')
    } finally {
      await electronApp.close()
    }
  })

  test('wheel over terminal does not zoom canvas', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-wheel',
          title: 'terminal-wheel',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
      ])

      const terminal = window.locator('.terminal-node').first()
      await expect(terminal).toBeVisible()
      await expect(terminal.locator('.xterm')).toBeVisible()

      const viewport = window.locator('.react-flow__viewport')
      const beforeTransform = await viewport.getAttribute('style')

      await terminal.hover()
      await window.mouse.wheel(0, -1200)

      const afterTransform = await viewport.getAttribute('style')
      expect(afterTransform).toBe(beforeTransform)
      await expect(terminal.locator('.xterm')).toBeVisible()
    } finally {
      await electronApp.close()
    }
  })

  test('renders subdued canvas controls and collapsible minimap', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-controls-minimap',
          title: 'terminal-controls-minimap',
          position: { x: 180, y: 140 },
          width: 460,
          height: 300,
        },
      ])

      const controls = window.locator('.workspace-canvas__controls')
      await expect(controls).toBeVisible()

      const controlsOpacity = await controls.evaluate(element => {
        return Number.parseFloat(window.getComputedStyle(element).opacity)
      })
      expect(controlsOpacity).toBeLessThan(0.8)

      const minimapToggle = window.locator('[data-testid="workspace-minimap-toggle"]')
      const minimap = window.locator('.workspace-canvas__minimap')
      await expect(minimap).toBeVisible()

      const minimapOpacity = await minimap.evaluate(element => {
        return Number.parseFloat(window.getComputedStyle(element).opacity)
      })
      expect(minimapOpacity).toBeLessThan(0.5)

      await expect(minimapToggle).toHaveCSS('visibility', 'hidden')

      await window.locator('.workspace-canvas__minimap-dock').hover()
      await expect(minimapToggle).toBeVisible()
      await expect(minimapToggle).toHaveCSS('visibility', 'visible')
      await expect(minimapToggle).toHaveAttribute('aria-label', 'Hide minimap')

      await minimapToggle.click()
      await expect(minimap).toHaveCount(0)
      await expect(minimapToggle).toBeVisible()
      await expect(minimapToggle).toHaveCSS('visibility', 'visible')
      await expect(minimapToggle).toHaveAttribute('aria-label', 'Show minimap')

      await minimapToggle.click()
      await expect(minimap).toBeVisible()
      await window.locator('.workspace-canvas .react-flow__pane').hover()
      await expect(minimapToggle).toHaveCSS('visibility', 'hidden')
      await expect(minimapToggle).toHaveAttribute('aria-label', 'Hide minimap')
    } finally {
      await electronApp.close()
    }
  })

  test('dragging terminal header does not normalize canvas zoom', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-header-zoom',
          title: 'terminal-header-zoom',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
      ])

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()

      await zoomInButton.click()
      await zoomInButton.click()

      const readZoom = async (): Promise<number> => {
        return await window.evaluate(() => {
          const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null
          if (!viewport) {
            return 1
          }

          const style = window.getComputedStyle(viewport)
          const matrix = style.transform.match(/matrix\(([^)]+)\)/)
          if (!matrix) {
            return 1
          }

          const values = matrix[1].split(',').map(item => Number(item.trim()))
          const zoom = values[0]
          return Number.isFinite(zoom) ? zoom : 1
        })
      }

      const zoomBefore = await readZoom()
      expect(zoomBefore).toBeGreaterThan(1.01)

      const terminal = window.locator('.terminal-node').first()
      await expect(terminal).toBeVisible()

      const header = terminal.locator('.terminal-node__header')
      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await header.dragTo(pane, {
        sourcePosition: { x: 120, y: 16 },
        targetPosition: { x: 680, y: 420 },
      })

      await expect
        .poll(async () => {
          return await readZoom()
        })
        .toBeGreaterThan(1.01)

      await terminal.locator('.xterm').click()

      await expect
        .poll(async () => {
          return await readZoom()
        })
        .toBeCloseTo(1, 2)
    } finally {
      await electronApp.close()
    }
  })

  test('normalizes canvas zoom and centers clicked terminal', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-zoom-1',
          title: 'terminal-zoom-1',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
        {
          id: 'node-zoom-2',
          title: 'terminal-zoom-2',
          position: { x: 820, y: 520 },
          width: 460,
          height: 300,
        },
      ])

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()

      await zoomInButton.click()
      await zoomInButton.click()

      const readZoom = async (): Promise<number> => {
        return await window.evaluate(() => {
          const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null
          if (!viewport) {
            return 1
          }

          const style = window.getComputedStyle(viewport)
          const matrix = style.transform.match(/matrix\(([^)]+)\)/)
          if (!matrix) {
            return 1
          }

          const values = matrix[1].split(',').map(item => Number(item.trim()))
          const zoom = values[0]
          return Number.isFinite(zoom) ? zoom : 1
        })
      }

      const zoomBefore = await readZoom()
      expect(zoomBefore).toBeGreaterThan(1.01)

      const firstTerminal = window.locator('.terminal-node').filter({ hasText: 'terminal-zoom-1' })
      await expect(firstTerminal).toBeVisible()
      await firstTerminal.locator('.xterm').click()

      await expect
        .poll(async () => {
          return await readZoom()
        })
        .toBeCloseTo(1, 2)

      const secondTerminal = window.locator('.terminal-node').filter({ hasText: 'terminal-zoom-2' })
      await expect(secondTerminal).toBeVisible()
      await secondTerminal.locator('.xterm').click()

      const readCenterDelta = async (): Promise<{ dx: number; dy: number }> => {
        const canvasBox = await window.locator('.workspace-canvas .react-flow').boundingBox()
        const terminalBox = await secondTerminal.boundingBox()

        if (!canvasBox || !terminalBox) {
          return {
            dx: Number.POSITIVE_INFINITY,
            dy: Number.POSITIVE_INFINITY,
          }
        }

        const canvasCenterX = canvasBox.x + canvasBox.width / 2
        const canvasCenterY = canvasBox.y + canvasBox.height / 2
        const terminalCenterX = terminalBox.x + terminalBox.width / 2
        const terminalCenterY = terminalBox.y + terminalBox.height / 2

        return {
          dx: Math.abs(canvasCenterX - terminalCenterX),
          dy: Math.abs(canvasCenterY - terminalCenterY),
        }
      }

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dx
        })
        .toBeLessThan(140)

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dy
        })
        .toBeLessThan(140)
    } finally {
      await electronApp.close()
    }
  })

  test('preserves terminal history after workspace switch', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await seedWorkspaceState(window, {
        activeWorkspaceId: 'workspace-a',
        workspaces: [
          {
            id: 'workspace-a',
            name: 'workspace-a',
            path: testWorkspacePath,
            nodes: [
              {
                id: 'node-a',
                title: 'terminal-a',
                position: { x: 120, y: 120 },
                width: 460,
                height: 300,
              },
            ],
          },
          {
            id: 'workspace-b',
            name: 'workspace-b',
            path: testWorkspacePath,
            nodes: [
              {
                id: 'node-b',
                title: 'terminal-b',
                position: { x: 160, y: 160 },
                width: 460,
                height: 300,
              },
            ],
          },
        ],
      })

      const terminal = window.locator('.terminal-node').first()
      await expect(terminal).toBeVisible()
      await expect(terminal.locator('.xterm')).toBeVisible()

      const token = `COVE_PERSIST_${Date.now()}`
      await terminal.locator('.xterm').click()
      await window.keyboard.type(`echo ${token}`)
      await window.keyboard.press('Enter')
      await expect(terminal).toContainText(token)

      await window.locator('.workspace-item').nth(1).click()
      await expect(window.locator('.workspace-item').nth(1)).toHaveClass(/workspace-item--active/)
      await expect(window.locator('.terminal-node')).toHaveCount(1)

      await window.locator('.workspace-item').nth(0).click()
      await expect(window.locator('.workspace-item').nth(0)).toHaveClass(/workspace-item--active/)
      await expect(window.locator('.terminal-node')).toHaveCount(1)
      await expect(window.locator('.terminal-node').first()).toContainText(token)
    } finally {
      await electronApp.close()
    }
  })

  test('preserves terminal history after app reload', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-reload',
          title: 'terminal-reload',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
      ])

      const terminal = window.locator('.terminal-node').first()
      await expect(terminal).toBeVisible()
      await expect(terminal.locator('.xterm')).toBeVisible()

      const token = `COVE_RELOAD_${Date.now()}`
      await terminal.locator('.xterm').click()
      await window.keyboard.type(`echo ${token}`)
      await window.keyboard.press('Enter')
      await expect(terminal).toContainText(token)

      await expect
        .poll(
          async () => {
            return await window.evaluate(
              ({ key, nodeId, expected }) => {
                const raw = window.localStorage.getItem(key)
                if (!raw) {
                  return false
                }

                const parsed = JSON.parse(raw) as {
                  workspaces?: Array<{
                    id?: string
                    nodes?: Array<{
                      id?: string
                      scrollback?: string | null
                    }>
                  }>
                }

                const workspace = parsed.workspaces?.find(item => item.id === 'workspace-seeded')
                const node = workspace?.nodes?.find(item => item.id === nodeId)
                return typeof node?.scrollback === 'string' && node.scrollback.includes(expected)
              },
              {
                key: storageKey,
                nodeId: 'node-reload',
                expected: token,
              },
            )
          },
          { timeout: 10_000 },
        )
        .toBe(true)

      await window.reload({ waitUntil: 'domcontentloaded' })

      const reloadedTerminal = window.locator('.terminal-node').first()
      await expect(reloadedTerminal).toBeVisible()
      await expect(reloadedTerminal.locator('.xterm')).toBeVisible()
      await expect(reloadedTerminal).toContainText(token)
    } finally {
      await electronApp.close()
    }
  })

  test('preserves canvas viewport and minimap visibility after app reload', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-viewport-reload',
          title: 'terminal-viewport-reload',
          position: { x: 360, y: 280 },
          width: 460,
          height: 300,
        },
      ])

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()
      await zoomInButton.click()
      await zoomInButton.click()

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()
      await pane.dragTo(pane, {
        sourcePosition: { x: 420, y: 320 },
        targetPosition: { x: 260, y: 220 },
      })

      const minimapDock = window.locator('.workspace-canvas__minimap-dock')
      await minimapDock.hover()
      const minimapToggle = window.locator('[data-testid="workspace-minimap-toggle"]')
      await expect(minimapToggle).toBeVisible()
      await minimapToggle.click()
      await expect(window.locator('.workspace-canvas__minimap')).toHaveCount(0)

      await expect
        .poll(
          async () => {
            return await window.evaluate(
              ({ key, workspaceId }) => {
                const raw = window.localStorage.getItem(key)
                if (!raw) {
                  return null
                }

                const parsed = JSON.parse(raw) as {
                  workspaces?: Array<{
                    id?: string
                    viewport?: {
                      x?: number
                      y?: number
                      zoom?: number
                    }
                    isMinimapVisible?: boolean
                  }>
                }

                const workspace = parsed.workspaces?.find(item => item.id === workspaceId)
                if (!workspace?.viewport) {
                  return null
                }

                const { x, y, zoom } = workspace.viewport
                if (
                  typeof x !== 'number' ||
                  typeof y !== 'number' ||
                  typeof zoom !== 'number' ||
                  !Number.isFinite(x) ||
                  !Number.isFinite(y) ||
                  !Number.isFinite(zoom)
                ) {
                  return null
                }

                return {
                  x,
                  y,
                  zoom,
                  isMinimapVisible:
                    typeof workspace.isMinimapVisible === 'boolean'
                      ? workspace.isMinimapVisible
                      : true,
                }
              },
              {
                key: storageKey,
                workspaceId: seededWorkspaceId,
              },
            )
          },
          { timeout: 10_000 },
        )
        .toMatchObject({
          isMinimapVisible: false,
        })

      const persistedViewport = await window.evaluate<{
        x: number
        y: number
        zoom: number
      } | null>(
        ({ key, workspaceId }) => {
          const raw = window.localStorage.getItem(key)
          if (!raw) {
            return null
          }

          const parsed = JSON.parse(raw) as {
            workspaces?: Array<{
              id?: string
              viewport?: {
                x?: number
                y?: number
                zoom?: number
              }
            }>
          }
          const workspace = parsed.workspaces?.find(item => item.id === workspaceId)
          const viewport = workspace?.viewport
          if (
            !viewport ||
            typeof viewport.x !== 'number' ||
            typeof viewport.y !== 'number' ||
            typeof viewport.zoom !== 'number'
          ) {
            return null
          }

          return viewport
        },
        {
          key: storageKey,
          workspaceId: seededWorkspaceId,
        },
      )

      if (!persistedViewport) {
        throw new Error('Persisted viewport not found after canvas interactions')
      }

      await window.reload({ waitUntil: 'domcontentloaded' })
      await expect(window.locator('.workspace-canvas__minimap')).toHaveCount(0)

      await expect
        .poll(async () => {
          const current = await readCanvasViewport(window)
          return current.zoom
        })
        .toBeCloseTo(persistedViewport.zoom, 2)

      await expect
        .poll(async () => {
          const current = await readCanvasViewport(window)
          return Math.abs(current.x - persistedViewport.x)
        })
        .toBeLessThan(6)

      await expect
        .poll(async () => {
          const current = await readCanvasViewport(window)
          return Math.abs(current.y - persistedViewport.y)
        })
        .toBeLessThan(6)
    } finally {
      await electronApp.close()
    }
  })

  test('wheel over terminal scrolls terminal viewport', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'node-scroll',
          title: 'terminal-scroll',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
        },
      ])

      const terminal = window.locator('.terminal-node').first()
      await expect(terminal).toBeVisible()
      const terminalInput = terminal.locator('.xterm-helper-textarea')
      await expect(terminalInput).toBeVisible()
      await terminalInput.click()
      await window.keyboard.type('for i in $(seq 1 260); do echo COVE_SCROLL_$i; done')
      await terminalInput.press('Enter')
      await expect(terminal).toContainText('COVE_SCROLL_260')

      const viewport = terminal.locator('.xterm-viewport')
      await expect(viewport).toBeVisible()

      const visibleRows = terminal.locator('.xterm-rows')
      const beforeRows = await visibleRows.innerText()

      await terminal.hover()
      await window.mouse.wheel(0, -1200)
      await window.waitForTimeout(120)

      const afterRows = await visibleRows.innerText()
      expect(afterRows).not.toBe(beforeRows)
    } finally {
      await electronApp.close()
    }
  })

  test('runs agent from launcher v2 and creates node', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [], {
        settings: {
          defaultProvider: 'codex',
          customModelEnabledByProvider: {
            'claude-code': false,
            codex: true,
          },
          customModelByProvider: {
            'claude-code': '',
            codex: 'gpt-5.2-codex',
          },
          customModelOptionsByProvider: {
            'claude-code': [],
            codex: ['gpt-5.2-codex'],
          },
        },
      })

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 320, y: 220 },
      })

      const runButton = window.locator('[data-testid="workspace-context-run-default-agent"]')
      await expect(runButton).toBeVisible()
      await runButton.click()

      const launcher = window.locator('[data-testid="workspace-agent-launcher"]')
      await expect(launcher).toBeVisible()

      await window.locator('[data-testid="workspace-agent-launch-provider"]').selectOption('codex')
      await window.locator('[data-testid="workspace-agent-launch-model"]').fill('gpt-5.2-codex')

      const promptInput = window.locator('[data-testid="workspace-agent-launch-prompt"]')
      await promptInput.fill('Generate implementation plan for API error handling')

      const submitButton = window.locator('[data-testid="workspace-agent-launch-submit"]')
      await submitButton.click()

      await expect(window.locator('.terminal-node')).toHaveCount(1)
      await expect(window.locator('.terminal-node__title').first()).toContainText('gpt-5.2-codex')
      await expect(window.locator('.terminal-node').first().locator('.xterm')).toBeVisible()
      await expect(window.locator('.terminal-node').first()).toContainText(
        '[cove-test-agent] codex new',
      )
      await expect(window.locator('.workspace-agent-item')).toHaveCount(1)
    } finally {
      await electronApp.close()
    }
  })

  test('does not allow creating space from empty shift box selection', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [])

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()
      const paneBox = await pane.boundingBox()
      if (!paneBox) {
        throw new Error('workspace pane bounding box unavailable')
      }

      const startX = paneBox.x + 140
      const startY = paneBox.y + 120

      await window.keyboard.down('Shift')
      await window.mouse.move(startX, startY)
      await window.mouse.down()
      await window.mouse.move(startX + 220, startY + 170, { steps: 8 })
      await window.mouse.up()
      await window.keyboard.up('Shift')

      await expect(
        window.locator('[data-testid="workspace-empty-selection-create-space"]'),
      ).toHaveCount(0)
      await expect(window.locator('.workspace-sidebar__space-label')).toHaveText('Space: All')

      const spaceCount = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return 0
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            spaces?: unknown[]
          }>
        }

        return parsed.workspaces?.[0]?.spaces?.length ?? 0
      }, storageKey)

      expect(spaceCount).toBe(0)
    } finally {
      await electronApp.close()
    }
  })

  test('opens pane menu on blank right-click even when node is selected', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'space-pane-menu-node',
          title: 'terminal-space-pane-menu',
          position: { x: 220, y: 180 },
          width: 460,
          height: 300,
        },
      ])

      const terminalNode = window.locator('.terminal-node').first()
      await expect(terminalNode).toBeVisible()
      await terminalNode.click()

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await pane.click({
        button: 'right',
        position: { x: 80, y: 80 },
      })

      await expect(window.locator('[data-testid="workspace-context-new-terminal"]')).toBeVisible()
      await expect(window.locator('[data-testid="workspace-selection-create-space"]')).toHaveCount(
        0,
      )
    } finally {
      await electronApp.close()
    }
  })

  test('removes empty selected-created space when all members are unassigned', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'space-cleanup-node',
          title: 'terminal-space-cleanup',
          position: { x: 220, y: 180 },
          width: 460,
          height: 300,
        },
      ])

      const terminalNode = window.locator('.terminal-node').first()
      await expect(terminalNode).toBeVisible()

      await terminalNode.click()
      await terminalNode.click({ button: 'right' })
      await window.locator('[data-testid="workspace-selection-create-space"]').click()

      await expect(window.locator('.workspace-sidebar__space-label')).toContainText('Space')

      await terminalNode.click({ button: 'right' })
      await window.locator('[data-testid="workspace-selection-remove-space"]').click()

      await expect(window.locator('.workspace-sidebar__space-label')).toHaveText('Space: All')
      await expect(window.locator('.workspace-space-switcher')).toHaveCount(0)

      const spaceCount = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return 0
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            spaces?: unknown[]
          }>
        }

        return parsed.workspaces?.[0]?.spaces?.length ?? 0
      }, storageKey)

      expect(spaceCount).toBe(0)
    } finally {
      await electronApp.close()
    }
  })

  test('renames space by clicking the region label', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'space-rename-node',
          title: 'terminal-space-rename',
          position: { x: 220, y: 180 },
          width: 460,
          height: 300,
        },
      ])

      const terminalNode = window.locator('.terminal-node').first()
      await expect(terminalNode).toBeVisible()

      await terminalNode.click()
      await terminalNode.click({ button: 'right' })
      await window.locator('[data-testid="workspace-selection-create-space"]').click()

      const labelButton = window.locator('.workspace-space-region__label').first()
      await expect(labelButton).toBeVisible()
      await labelButton.click()

      const renameInput = window.locator('.workspace-space-region__label-input').first()
      await expect(renameInput).toBeVisible()
      await renameInput.fill('Infra Core')
      await renameInput.press('Enter')

      await expect(window.locator('.workspace-sidebar__space-label')).toHaveText(
        'Space: Infra Core',
      )
      await expect(
        window.locator('.workspace-space-switcher__item', { hasText: 'Infra Core' }),
      ).toBeVisible()
    } finally {
      await electronApp.close()
    }
  })

  test('fits space bounds in viewport when clicking a space switch item', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-focus-node',
            title: 'terminal-space-focus',
            position: { x: 1740, y: 1120 },
            width: 460,
            height: 300,
          },
        ],
        {
          spaces: [
            {
              id: 'space-focus',
              name: 'Focus Scope',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-focus-node'],
              rect: {
                x: 1700,
                y: 1080,
                width: 540,
                height: 380,
              },
            },
          ],
          activeSpaceId: null,
        },
      )

      const beforeViewport = await readCanvasViewport(window)
      expect(Math.abs(beforeViewport.x)).toBeLessThan(40)
      expect(Math.abs(beforeViewport.y)).toBeLessThan(40)

      const canvasBounds = await window.evaluate(() => {
        const surface = document.querySelector('.workspace-canvas .react-flow')
        if (!(surface instanceof HTMLElement)) {
          return null
        }

        return {
          width: surface.clientWidth,
          height: surface.clientHeight,
        }
      })

      if (!canvasBounds) {
        throw new Error('react-flow surface size unavailable')
      }

      const targetSpace = {
        x: 1700,
        y: 1080,
        width: 540,
        height: 380,
      }

      await window.locator('[data-testid="workspace-space-switch-space-focus"]').click()
      await expect(window.locator('.workspace-sidebar__space-label')).toHaveText(
        'Space: Focus Scope',
      )

      await expect
        .poll(async () => {
          const viewport = await readCanvasViewport(window)
          const minFlowX = -viewport.x / viewport.zoom
          const maxFlowX = (canvasBounds.width - viewport.x) / viewport.zoom

          return {
            minFlowX,
            maxFlowX,
          }
        })
        .toEqual(
          expect.objectContaining({
            minFlowX: expect.any(Number),
            maxFlowX: expect.any(Number),
          }),
        )

      await expect
        .poll(async () => {
          const viewport = await readCanvasViewport(window)
          const minFlowX = -viewport.x / viewport.zoom
          const maxFlowX = (canvasBounds.width - viewport.x) / viewport.zoom
          return {
            leftVisible: minFlowX <= targetSpace.x + 1,
            rightVisible: maxFlowX >= targetSpace.x + targetSpace.width - 1,
          }
        })
        .toEqual({
          leftVisible: true,
          rightVisible: true,
        })

      await expect
        .poll(async () => {
          const viewport = await readCanvasViewport(window)
          const minFlowY = -viewport.y / viewport.zoom
          const maxFlowY = (canvasBounds.height - viewport.y) / viewport.zoom
          return {
            topVisible: minFlowY <= targetSpace.y + 1,
            bottomVisible: maxFlowY >= targetSpace.y + targetSpace.height - 1,
          }
        })
        .toEqual({
          topVisible: true,
          bottomVisible: true,
        })
    } finally {
      await electronApp.close()
    }
  })

  test('renders space overlay layer below node windows', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-layer-node',
            title: 'terminal-space-layer',
            position: { x: 360, y: 260 },
            width: 460,
            height: 300,
          },
        ],
        {
          spaces: [
            {
              id: 'space-layer',
              name: 'Layer Scope',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-layer-node'],
              rect: {
                x: 320,
                y: 220,
                width: 540,
                height: 380,
              },
            },
          ],
          activeSpaceId: 'space-layer',
        },
      )

      const levels = await window.evaluate(() => {
        const overlayLayer = document.querySelector(
          '.workspace-canvas .react-flow__viewport-portal',
        ) as HTMLElement | null
        const nodeLayer = document.querySelector(
          '.workspace-canvas .react-flow__nodes',
        ) as HTMLElement | null

        if (!overlayLayer || !nodeLayer) {
          return null
        }

        const parseLevel = (value: string): number => {
          if (value === 'auto') {
            return 0
          }

          const parsed = Number.parseInt(value, 10)
          return Number.isNaN(parsed) ? 0 : parsed
        }

        return {
          overlay: parseLevel(window.getComputedStyle(overlayLayer).zIndex),
          node: parseLevel(window.getComputedStyle(nodeLayer).zIndex),
        }
      })

      if (!levels) {
        throw new Error('unable to read overlay/node z-index levels')
      }

      expect(levels.overlay).toBeLessThan(levels.node)
    } finally {
      await electronApp.close()
    }
  })

  test('drags explicit space border and moves enclosed nodes together', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-drag-node',
            title: 'terminal-space-drag',
            position: { x: 420, y: 340 },
            width: 460,
            height: 300,
          },
        ],
        {
          spaces: [
            {
              id: 'space-drag',
              name: 'Drag Scope',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-drag-node'],
              rect: {
                x: 340,
                y: 280,
                width: 620,
                height: 420,
              },
            },
          ],
          activeSpaceId: 'space-drag',
        },
      )

      const readPersistedSpaceAndNode = async (): Promise<{
        nodeX: number
        nodeY: number
        rectX: number
        rectY: number
      } | null> => {
        return await window.evaluate(
          ({ key, nodeId, spaceId }) => {
            const raw = window.localStorage.getItem(key)
            if (!raw) {
              return null
            }

            const parsed = JSON.parse(raw) as {
              workspaces?: Array<{
                nodes?: Array<{
                  id?: string
                  position?: {
                    x?: number
                    y?: number
                  }
                }>
                spaces?: Array<{
                  id?: string
                  rect?: {
                    x?: number
                    y?: number
                  } | null
                }>
              }>
            }

            const workspace = parsed.workspaces?.[0]
            if (!workspace) {
              return null
            }

            const node = workspace.nodes?.find(item => item.id === nodeId)
            const space = workspace.spaces?.find(item => item.id === spaceId)
            if (!node?.position || !space?.rect) {
              return null
            }

            if (
              typeof node.position.x !== 'number' ||
              typeof node.position.y !== 'number' ||
              typeof space.rect.x !== 'number' ||
              typeof space.rect.y !== 'number'
            ) {
              return null
            }

            return {
              nodeX: node.position.x,
              nodeY: node.position.y,
              rectX: space.rect.x,
              rectY: space.rect.y,
            }
          },
          {
            key: storageKey,
            nodeId: 'space-drag-node',
            spaceId: 'space-drag',
          },
        )
      }

      const before = await readPersistedSpaceAndNode()
      if (!before) {
        throw new Error('failed to read initial persisted space/node state')
      }

      const dragHandle = window.locator('[data-testid="workspace-space-drag-space-drag-top"]')
      await expect(dragHandle).toBeVisible()

      const handleBox = await dragHandle.boundingBox()
      if (!handleBox) {
        throw new Error('space drag handle bounding box unavailable')
      }

      const startX = handleBox.x + handleBox.width * 0.5
      const startY = handleBox.y + handleBox.height * 0.5
      const dragDx = 160
      const dragDy = 110

      await window.mouse.move(startX, startY)
      await window.mouse.down()
      await window.mouse.move(startX + dragDx, startY + dragDy, { steps: 12 })
      await window.mouse.up()

      await expect
        .poll(async () => {
          const after = await readPersistedSpaceAndNode()
          return after ? after.nodeX - before.nodeX : Number.NaN
        })
        .toBeGreaterThan(120)

      await expect
        .poll(async () => {
          const after = await readPersistedSpaceAndNode()
          return after ? after.nodeY - before.nodeY : Number.NaN
        })
        .toBeGreaterThan(80)

      await expect
        .poll(async () => {
          const after = await readPersistedSpaceAndNode()
          return after ? after.rectX - before.rectX : Number.NaN
        })
        .toBeGreaterThan(120)

      await expect
        .poll(async () => {
          const after = await readPersistedSpaceAndNode()
          return after ? after.rectY - before.rectY : Number.NaN
        })
        .toBeGreaterThan(80)
    } finally {
      await electronApp.close()
    }
  })

  test('blocks moving selected agent to workspace with different directory', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-agent-node',
            title: 'codex · gpt-5.2-codex',
            position: { x: 260, y: 180 },
            width: 500,
            height: 320,
            kind: 'agent',
            status: 'running',
            startedAt: new Date().toISOString(),
            endedAt: null,
            exitCode: null,
            lastError: null,
            scrollback: '[cove-test-agent] codex new gpt-5.2-codex\n',
            agent: {
              provider: 'codex',
              prompt: 'Implement API retries',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'new',
              resumeSessionId: null,
              executionDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
            },
            task: null,
          },
          {
            id: 'space-anchor-node',
            title: 'terminal-space-anchor',
            position: { x: 980, y: 240 },
            width: 460,
            height: 300,
          },
        ],
        {
          spaces: [
            {
              id: 'space-diff',
              name: 'Worktree Scope',
              directoryPath: `${testWorkspacePath}/.cove/worktrees/demo`,
              nodeIds: ['space-anchor-node'],
              rect: {
                x: 900,
                y: 220,
                width: 240,
                height: 180,
              },
            },
          ],
        },
      )

      const agentNode = window.locator('.terminal-node').first()
      await expect(agentNode).toBeVisible()
      await agentNode.click()
      await agentNode.click({ button: 'right' })

      const moveButton = window.locator('[data-testid="workspace-selection-move-space-space-diff"]')
      await expect(moveButton).toBeVisible()

      const alertPromise = window.waitForEvent('dialog').then(async dialog => {
        expect(dialog.type()).toBe('alert')
        const message = dialog.message()
        await dialog.accept()
        return message
      })

      await moveButton.click()
      const alertMessage = await alertPromise
      expect(alertMessage).toContain('directory')

      const movedToDifferentSpace = await window.evaluate(
        ({ key, nodeId, targetSpaceId }) => {
          const raw = window.localStorage.getItem(key)
          if (!raw) {
            return false
          }

          const parsed = JSON.parse(raw) as {
            workspaces?: Array<{
              spaces?: Array<{
                id?: string
                nodeIds?: string[]
              }>
            }>
          }
          const spaces = parsed.workspaces?.[0]?.spaces ?? []
          const targetSpace = spaces.find(space => space.id === targetSpaceId)
          return Array.isArray(targetSpace?.nodeIds) ? targetSpace.nodeIds.includes(nodeId) : false
        },
        {
          key: storageKey,
          nodeId: 'space-agent-node',
          targetSpaceId: 'space-diff',
        },
      )

      expect(movedToDifferentSpace).toBe(false)
    } finally {
      await electronApp.close()
    }
  })

  test('creates task node with auto title and runs linked agent', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [], {
        settings: {
          defaultProvider: 'codex',
          customModelEnabledByProvider: {
            'claude-code': false,
            codex: true,
          },
          customModelByProvider: {
            'claude-code': '',
            codex: 'gpt-5.2-codex',
          },
          customModelOptionsByProvider: {
            'claude-code': [],
            codex: ['gpt-5.2-codex'],
          },
          taskTitleProvider: 'codex',
          taskTitleModel: 'gpt-5.2-codex',
          taskTagOptions: ['auth', 'retry'],
        },
      })

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 320, y: 220 },
      })

      await window.locator('[data-testid="workspace-context-new-task"]').click()

      const taskCreator = window.locator('[data-testid="workspace-task-creator"]')
      await expect(taskCreator).toBeVisible()

      const requirement = window.locator('[data-testid="workspace-task-requirement"]')
      await requirement.fill('Implement login retry with exponential backoff and jitter')

      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()
      await expect(taskNode.locator('.task-node__title')).toContainText('Auto:')
      await expect(taskNode.locator('.task-node__priority')).toHaveText('MEDIUM')
      await expect(taskNode.locator('[data-testid="task-node-tags"]')).toContainText('#auth')

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      await expect(window.locator('.terminal-node')).toHaveCount(1)
      await expect(window.locator('.workspace-agent-item')).toHaveCount(1)

      const taskStatus = taskNode.locator('[data-testid="task-node-status-select"]')
      await expect(taskStatus).toHaveValue('doing')

      const persisted = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              kind?: string
              title?: string
              task?: {
                requirement?: string
                priority?: string
                tags?: string[]
                autoGeneratedTitle?: boolean
              }
            }>
          }>
        }

        return parsed.workspaces?.[0]?.nodes?.find(node => node.kind === 'task') ?? null
      }, storageKey)

      expect(persisted).toBeTruthy()
      expect(persisted?.task?.requirement).toContain('exponential backoff')
      expect(persisted?.task?.priority).toBe('medium')
      expect(persisted?.task?.tags).toEqual(['auth'])
      expect(persisted?.task?.autoGeneratedTitle).toBe(true)
    } finally {
      await electronApp.close()
    }
  })

  test('supports manual task assignment and renders task-agent cable', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'task-assign-1',
          title: 'Prepare release notes',
          position: { x: 180, y: 140 },
          width: 460,
          height: 280,
          kind: 'task',
          status: null,
          task: {
            requirement: 'Summarize user-facing changes for this release',
            status: 'todo',
            priority: 'medium',
            tags: ['release'],
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: '2026-02-12T09:30:00.000Z',
            updatedAt: '2026-02-12T09:30:00.000Z',
          },
        },
        {
          id: 'agent-assign-1',
          title: 'codex · gpt-5.2-codex',
          position: { x: 760, y: 180 },
          width: 520,
          height: 360,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-12T09:40:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: '[cove-test-agent] ready',
          agent: {
            provider: 'codex',
            prompt: 'Summarize release notes',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'new',
            resumeSessionId: null,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
      ])

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-assign-agent"]').click()

      const assigner = window.locator('[data-testid="workspace-task-assigner"]')
      await expect(assigner).toBeVisible()

      await window
        .locator('[data-testid="workspace-task-assign-select"]')
        .selectOption('agent-assign-1')
      await window.locator('[data-testid="workspace-task-assign-submit"]').click()

      await expect(assigner).toHaveCount(0)
      await expect(taskNode.locator('[data-testid="task-node-linked-agent"]')).toContainText(
        'codex · gpt-5.2-codex',
      )
      await expect(window.locator('.workspace-task-agent-edge')).toHaveCount(1)

      const persisted = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id?: string
              task?: {
                linkedAgentNodeId?: string | null
              }
              agent?: {
                taskId?: string | null
              }
            }>
          }>
        }

        const nodes = parsed.workspaces?.[0]?.nodes ?? []
        const taskNode = nodes.find(node => node.id === 'task-assign-1')
        const agentNode = nodes.find(node => node.id === 'agent-assign-1')

        return {
          taskLinkedAgentNodeId: taskNode?.task?.linkedAgentNodeId ?? null,
          agentTaskId: agentNode?.agent?.taskId ?? null,
        }
      }, storageKey)

      expect(persisted).toEqual({
        taskLinkedAgentNodeId: 'agent-assign-1',
        agentTaskId: 'task-assign-1',
      })
    } finally {
      await electronApp.close()
    }
  })

  test('supports agent controls and sidebar navigation', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'terminal-nav-node',
          title: 'terminal-1',
          position: { x: 120, y: 120 },
          width: 460,
          height: 300,
          kind: 'terminal',
        },
        {
          id: 'agent-nav-node',
          title: 'codex · gpt-5.2-codex',
          position: { x: 720, y: 460 },
          width: 520,
          height: 320,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-08T15:00:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          agent: {
            provider: 'codex',
            prompt: 'Implement resilient retry logic',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'new',
            resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
      ])

      const agentItem = window.locator('.workspace-agent-item').first()
      await expect(agentItem).toBeVisible()

      const zoomInButton = window.locator('.react-flow__controls-zoomin')
      await expect(zoomInButton).toBeVisible()
      await zoomInButton.click()
      await zoomInButton.click()

      const readZoom = async (): Promise<number> => {
        return await window.evaluate(() => {
          const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null
          if (!viewport) {
            return 1
          }

          const style = window.getComputedStyle(viewport)
          const matrix = style.transform.match(/matrix\(([^)]+)\)/)
          if (!matrix) {
            return 1
          }

          const values = matrix[1].split(',').map(item => Number(item.trim()))
          const zoom = values[0]
          return Number.isFinite(zoom) ? zoom : 1
        })
      }

      const zoomBefore = await readZoom()
      expect(zoomBefore).toBeGreaterThan(1.01)

      await agentItem.click()

      const agentNode = window
        .locator('.terminal-node')
        .filter({ has: window.locator('.terminal-node__title', { hasText: 'codex' }) })
        .first()

      await expect(agentNode).toBeVisible()

      await expect
        .poll(async () => {
          return await readZoom()
        })
        .toBeCloseTo(1, 2)

      const readCenterDelta = async (): Promise<{ dx: number; dy: number }> => {
        const canvasBox = await window.locator('.workspace-canvas .react-flow').boundingBox()
        const terminalBox = await agentNode.boundingBox()

        if (!canvasBox || !terminalBox) {
          return {
            dx: Number.POSITIVE_INFINITY,
            dy: Number.POSITIVE_INFINITY,
          }
        }

        const canvasCenterX = canvasBox.x + canvasBox.width / 2
        const canvasCenterY = canvasBox.y + canvasBox.height / 2
        const terminalCenterX = terminalBox.x + terminalBox.width / 2
        const terminalCenterY = terminalBox.y + terminalBox.height / 2

        return {
          dx: Math.abs(canvasCenterX - terminalCenterX),
          dy: Math.abs(canvasCenterY - terminalCenterY),
        }
      }

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dx
        })
        .toBeLessThan(140)

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return delta.dy
        })
        .toBeLessThan(140)
      await expect(agentNode.locator('.terminal-node__status')).toHaveText('Running')

      await agentNode.locator('.terminal-node__action', { hasText: 'Stop' }).click()
      await expect(agentNode.locator('.terminal-node__status')).toHaveText('Stopped')

      await agentNode.locator('.terminal-node__action', { hasText: 'Rerun' }).click()
      await expect(agentNode.locator('.terminal-node__status')).toHaveText(/Restoring|Running/)

      await expect(agentNode.locator('.terminal-node__status')).toHaveText('Running')

      await agentNode.locator('.terminal-node__action', { hasText: 'Resume' }).click()
      await expect(agentNode.locator('.terminal-node__status')).toHaveText(/Restoring|Running/)
      await expect(agentNode.locator('.terminal-node__status')).toHaveText('Running')

      const agentHeader = agentNode.locator('.terminal-node__header')
      await agentHeader.click()

      const fitViewButton = window.locator('.react-flow__controls-fitview')
      await expect(fitViewButton).toBeVisible()
      await fitViewButton.click()

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return Math.max(delta.dx, delta.dy)
        })
        .toBeGreaterThan(180)

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      const paneBox = await pane.boundingBox()
      if (!paneBox) {
        throw new Error('workspace pane bounding box unavailable')
      }

      await pane.click({
        position: {
          x: Math.floor(paneBox.width * 0.6),
          y: Math.floor(paneBox.height * 0.5),
        },
      })

      await expect
        .poll(async () => {
          const delta = await readCenterDelta()
          return Math.max(delta.dx, delta.dy)
        })
        .toBeGreaterThan(180)
    } finally {
      await electronApp.close()
    }
  })

  test('shows sidebar agent status and linked task title', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'task-status-doing',
          title: 'Implement OAuth refresh flow',
          position: { x: 80, y: 120 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Handle OAuth token refresh and retry once',
            status: 'doing',
            linkedAgentNodeId: 'agent-status-doing',
            lastRunAt: '2026-02-10T08:40:00.000Z',
            autoGeneratedTitle: false,
          },
        },
        {
          id: 'task-status-request',
          title: 'Clarify API contract with PM',
          position: { x: 80, y: 460 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'List unknown fields and ask for confirmation',
            status: 'doing',
            linkedAgentNodeId: 'agent-status-request',
            lastRunAt: '2026-02-10T09:00:00.000Z',
            autoGeneratedTitle: false,
          },
        },
        {
          id: 'task-status-done',
          title: 'Finalize migration checklist',
          position: { x: 80, y: 800 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Complete migration checklist and report',
            status: 'ai_done',
            linkedAgentNodeId: 'agent-status-done',
            lastRunAt: '2026-02-10T09:20:00.000Z',
            autoGeneratedTitle: false,
          },
        },
        {
          id: 'agent-status-doing',
          title: 'codex · gpt-5.2-codex',
          position: { x: 620, y: 120 },
          width: 520,
          height: 320,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-10T08:45:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          agent: {
            provider: 'codex',
            prompt: 'Implement OAuth refresh flow',
            model: 'gpt-5.2-codex',
            effectiveModel: 'gpt-5.2-codex',
            launchMode: 'new',
            resumeSessionId: null,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
        {
          id: 'agent-status-request',
          title: 'claude · claude-sonnet-4-5',
          position: { x: 620, y: 460 },
          width: 520,
          height: 320,
          kind: 'agent',
          status: 'exited',
          startedAt: '2026-02-10T09:00:00.000Z',
          endedAt: '2026-02-10T09:03:00.000Z',
          exitCode: 0,
          lastError: null,
          agent: {
            provider: 'claude-code',
            prompt: 'Clarify API contract with PM',
            model: 'claude-sonnet-4-5',
            effectiveModel: 'claude-sonnet-4-5',
            launchMode: 'new',
            resumeSessionId: null,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
        {
          id: 'agent-status-done',
          title: 'claude · claude-opus-4-6',
          position: { x: 620, y: 800 },
          width: 520,
          height: 320,
          kind: 'agent',
          status: 'running',
          startedAt: '2026-02-10T09:20:00.000Z',
          endedAt: null,
          exitCode: null,
          lastError: null,
          agent: {
            provider: 'claude-code',
            prompt: 'Finalize migration checklist',
            model: 'claude-opus-4-6',
            effectiveModel: 'claude-opus-4-6',
            launchMode: 'new',
            resumeSessionId: null,
            executionDirectory: testWorkspacePath,
            directoryMode: 'workspace',
            customDirectory: null,
            shouldCreateDirectory: false,
          },
        },
      ])

      const doingItem = window.locator(
        '[data-testid="workspace-agent-item-workspace-seeded-agent-status-doing"]',
      )
      const requestItem = window.locator(
        '[data-testid="workspace-agent-item-workspace-seeded-agent-status-request"]',
      )
      const doneItem = window.locator(
        '[data-testid="workspace-agent-item-workspace-seeded-agent-status-done"]',
      )

      const requestNode = window
        .locator('.terminal-node')
        .filter({
          has: window.locator('.terminal-node__title', {
            hasText: 'claude · claude-sonnet-4-5',
          }),
        })
        .first()

      await requestItem.click()
      await expect(requestNode).toBeVisible()
      await requestNode.locator('.terminal-node__action', { hasText: 'Stop' }).click()

      await expect(doingItem.locator('.workspace-agent-item__status--agent')).toHaveText('Working')
      await expect(requestItem.locator('.workspace-agent-item__status--agent')).toHaveText(
        'Standby',
      )
      await expect(doneItem.locator('.workspace-agent-item__status--agent')).toHaveText('Working')

      await expect(doingItem.locator('.workspace-agent-item__status--task')).toHaveText('DOING')
      await expect(requestItem.locator('.workspace-agent-item__status--task')).toHaveText('DOING')
      await expect(doneItem.locator('.workspace-agent-item__status--task')).toHaveText('AI_DONE')

      await expect(doingItem.locator('.workspace-agent-item__task-text')).toHaveText(
        'Implement OAuth refresh flow',
      )
      await expect(requestItem.locator('.workspace-agent-item__task-text')).toHaveText(
        'Clarify API contract with PM',
      )
      await expect(doneItem.locator('.workspace-agent-item__task-text')).toHaveText(
        'Finalize migration checklist',
      )
    } finally {
      await electronApp.close()
    }
  })

  test('supports task edit, resize, and delete confirmation', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'task-edit-node',
          title: 'Initial Task Title',
          position: { x: 180, y: 160 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Initial requirement text',
            status: 'todo',
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
          },
        },
      ])

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-inline-requirement-trigger"]').click()

      const inlineRequirementInput = taskNode.locator(
        '[data-testid="task-node-inline-requirement-input"]',
      )
      await expect(inlineRequirementInput).toBeVisible()
      await inlineRequirementInput.fill('Inline updated requirement from card')
      await inlineRequirementInput.blur()
      await expect(taskNode.locator('.task-node__content p')).toContainText(
        'Inline updated requirement from card',
      )

      await taskNode.locator('[data-testid="task-node-open-editor"]').click()

      const editor = window.locator('[data-testid="workspace-task-editor"]')
      await expect(editor).toBeVisible()

      await window
        .locator('[data-testid="workspace-task-editor-title"]')
        .fill('Retry login workflow')
      await window
        .locator('[data-testid="workspace-task-editor-requirement"]')
        .fill('Implement retry with capped exponential backoff and jitter')

      await window.locator('[data-testid="workspace-task-edit-submit"]').click()

      await expect(window.locator('.task-node__title').first()).toHaveText('Retry login workflow')
      await expect(taskNode.locator('.task-node__content p')).toContainText('capped exponential')

      const rightResizer = taskNode.locator('[data-testid="task-resizer-right"]')
      const rightResizerBox = await rightResizer.boundingBox()
      if (!rightResizerBox) {
        throw new Error('task right resizer bounding box unavailable')
      }

      const rightStartX = rightResizerBox.x + rightResizerBox.width / 2
      const rightStartY = rightResizerBox.y + rightResizerBox.height / 2

      await window.mouse.move(rightStartX, rightStartY)
      await window.mouse.down()
      await window.mouse.move(rightStartX + 120, rightStartY + 30)
      await window.mouse.up()

      const bottomResizer = taskNode.locator('[data-testid="task-resizer-bottom"]')
      const bottomResizerBox = await bottomResizer.boundingBox()
      if (!bottomResizerBox) {
        throw new Error('task bottom resizer bounding box unavailable')
      }

      const bottomStartX = bottomResizerBox.x + bottomResizerBox.width / 2
      const bottomStartY = bottomResizerBox.y + bottomResizerBox.height / 2

      await window.mouse.move(bottomStartX, bottomStartY)
      await window.mouse.down()
      await window.mouse.move(bottomStartX + 40, bottomStartY + 100)
      await window.mouse.up()

      const resizedTask = await window.evaluate(key => {
        const raw = window.localStorage.getItem(key)
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id: string
              width: number
              height: number
              title: string
              task?: {
                requirement?: string
              }
            }>
          }>
        }

        return parsed.workspaces?.[0]?.nodes?.find(node => node.id === 'task-edit-node') ?? null
      }, storageKey)

      expect(resizedTask).toBeTruthy()
      expect(resizedTask?.width ?? 0).toBeGreaterThan(460)
      expect(resizedTask?.height ?? 0).toBeGreaterThan(280)
      expect(resizedTask?.title).toBe('Retry login workflow')
      expect(resizedTask?.task?.requirement).toContain('capped exponential')

      await taskNode.locator('[data-testid="task-node-close"]').click()

      const deleteDialog = window.locator('[data-testid="workspace-task-delete-confirmation"]')
      await expect(deleteDialog).toBeVisible()

      await window.locator('[data-testid="workspace-task-delete-cancel"]').click()
      await expect(deleteDialog).toBeHidden()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-close"]').click()
      await expect(deleteDialog).toBeVisible()
      await window.locator('[data-testid="workspace-task-delete-confirm"]').click()

      await expect(window.locator('.task-node')).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })

  test('shows agents under each workspace and focuses selected workspace', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await seedWorkspaceState(window, {
        activeWorkspaceId: 'workspace-a',
        workspaces: [
          {
            id: 'workspace-a',
            name: 'workspace-a',
            path: testWorkspacePath,
            nodes: [
              {
                id: 'agent-node-a',
                title: 'codex · gpt-5.2-codex',
                position: { x: 120, y: 120 },
                width: 520,
                height: 320,
                kind: 'agent',
                status: 'running',
                startedAt: '2026-02-09T08:00:00.000Z',
                endedAt: null,
                exitCode: null,
                lastError: null,
                agent: {
                  provider: 'codex',
                  prompt: 'task a',
                  model: 'gpt-5.2-codex',
                  effectiveModel: 'gpt-5.2-codex',
                  launchMode: 'new',
                  resumeSessionId: null,
                  executionDirectory: testWorkspacePath,
                  directoryMode: 'workspace',
                  customDirectory: null,
                  shouldCreateDirectory: false,
                },
              },
            ],
          },
          {
            id: 'workspace-b',
            name: 'workspace-b',
            path: `${testWorkspacePath}-b`,
            nodes: [
              {
                id: 'agent-node-b',
                title: 'claude · claude-opus-4-6',
                position: { x: 560, y: 420 },
                width: 520,
                height: 320,
                kind: 'agent',
                status: 'running',
                startedAt: '2026-02-09T09:00:00.000Z',
                endedAt: null,
                exitCode: null,
                lastError: null,
                agent: {
                  provider: 'claude-code',
                  prompt: 'task b',
                  model: 'claude-opus-4-6',
                  effectiveModel: 'claude-opus-4-6',
                  launchMode: 'new',
                  resumeSessionId: null,
                  executionDirectory: `${testWorkspacePath}-b`,
                  directoryMode: 'workspace',
                  customDirectory: null,
                  shouldCreateDirectory: false,
                },
              },
            ],
          },
        ],
      })

      const workspaceAGroup = window
        .locator('.workspace-item-group')
        .filter({ has: window.locator('.workspace-item__name', { hasText: 'workspace-a' }) })
      const workspaceBGroup = window
        .locator('.workspace-item-group')
        .filter({ has: window.locator('.workspace-item__name', { hasText: 'workspace-b' }) })

      await expect(
        workspaceAGroup.locator('.workspace-item__agents .workspace-agent-item'),
      ).toHaveCount(1)
      await expect(
        workspaceBGroup.locator('.workspace-item__agents .workspace-agent-item'),
      ).toHaveCount(1)

      await expect(
        workspaceAGroup.locator('[data-testid="workspace-agent-item-workspace-a-agent-node-a"]'),
      ).toBeVisible()
      await expect(
        workspaceBGroup.locator('[data-testid="workspace-agent-item-workspace-b-agent-node-b"]'),
      ).toBeVisible()

      await window.locator('[data-testid="workspace-agent-item-workspace-b-agent-node-b"]').click()
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-b',
      )
      await expect(window.locator('.terminal-node__title').first()).toContainText('claude')

      await window.locator('[data-testid="workspace-agent-item-workspace-a-agent-node-a"]').click()
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-a',
      )
      await expect(window.locator('.terminal-node__title').first()).toContainText('codex')
    } finally {
      await electronApp.close()
    }
  })

  test('removes project from sidebar via right-click menu', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await seedWorkspaceState(window, {
        activeWorkspaceId: 'workspace-remove-b',
        workspaces: [
          {
            id: 'workspace-remove-a',
            name: 'workspace-remove-a',
            path: testWorkspacePath,
            nodes: [],
          },
          {
            id: 'workspace-remove-b',
            name: 'workspace-remove-b',
            path: `${testWorkspacePath}-b`,
            nodes: [],
          },
        ],
      })

      const targetWorkspace = window
        .locator('.workspace-item')
        .filter({ has: window.locator('.workspace-item__name', { hasText: 'workspace-remove-b' }) })
        .first()
      await expect(targetWorkspace).toBeVisible()

      await targetWorkspace.click({ button: 'right' })

      const removeButton = window.locator(
        '[data-testid="workspace-project-remove-workspace-remove-b"]',
      )
      await expect(removeButton).toBeVisible()

      await removeButton.click()

      const removeDialog = window.locator('[data-testid="workspace-project-delete-confirmation"]')
      await expect(removeDialog).toBeVisible()
      await expect(removeDialog).toContainText('workspace-remove-b')

      await window.locator('[data-testid="workspace-project-delete-confirm"]').click()
      await expect(removeDialog).toHaveCount(0)

      await expect(window.locator('.workspace-item')).toHaveCount(1)
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-remove-a',
      )

      await expect
        .poll(
          async () => {
            return await window.evaluate(key => {
              const raw = window.localStorage.getItem(key)
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                activeWorkspaceId?: string | null
                workspaces?: Array<{
                  id?: string
                }>
              }

              return {
                activeWorkspaceId:
                  typeof parsed.activeWorkspaceId === 'string' ? parsed.activeWorkspaceId : null,
                workspaceIds: (parsed.workspaces ?? [])
                  .map(workspace => (typeof workspace.id === 'string' ? workspace.id : ''))
                  .filter(id => id.length > 0),
              }
            }, storageKey)
          },
          { timeout: 10_000 },
        )
        .toEqual({
          activeWorkspaceId: 'workspace-remove-a',
          workspaceIds: ['workspace-remove-a'],
        })
    } finally {
      await electronApp.close()
    }
  })
})
