import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, storageKey } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Node Create (Push-away)', () => {
  test('pushes blocking windows to the right when creating a task in a crowded spot', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'crowded-existing-task',
          title: 'existing-task',
          position: { x: 320, y: 220 },
          width: 460,
          height: 280,
          kind: 'task',
          status: null,
          task: {
            requirement: 'existing',
            status: 'todo',
            priority: 'medium',
            tags: [],
            linkedAgentNodeId: null,
            agentSessions: [],
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: '2026-02-15T00:00:00.000Z',
            updatedAt: '2026-02-15T00:00:00.000Z',
          },
        },
      ])

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 280, y: 220 },
      })
      await window.locator('[data-testid="workspace-context-new-task"]').click()

      await expect(window.locator('[data-testid="workspace-task-creator"]')).toBeVisible()
      await window.locator('[data-testid="workspace-task-advanced-toggle"]').click()
      await window.locator('[data-testid="workspace-task-title"]').fill('Crowded Task')
      await window.locator('[data-testid="workspace-task-requirement"]').fill('push-away-on-create')
      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      await expect(window.locator('.task-node')).toHaveCount(2)

      const snapshot = await window.evaluate(async key => {
        void key

        const raw = await window.coveApi.persistence.readWorkspaceStateRaw()
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id?: string
              kind?: string
              position?: { x?: number; y?: number }
              task?: { requirement?: string } | null
            }>
          }>
        }

        const workspace = parsed.workspaces?.[0]
        const nodes = workspace?.nodes ?? []
        const created = nodes.find(
          node => node.kind === 'task' && node.task?.requirement === 'push-away-on-create',
        )
        const existing = nodes.find(node => node.id === 'crowded-existing-task')

        if (
          !created?.position ||
          typeof created.position.x !== 'number' ||
          typeof created.width !== 'number' ||
          !existing?.position ||
          typeof existing.position.x !== 'number'
        ) {
          return null
        }

        return {
          createdX: created.position.x,
          createdWidth: created.width,
          existingX: existing.position.x,
        }
      }, storageKey)

      if (!snapshot) {
        throw new Error('failed to read persisted crowded create snapshot')
      }

      expect(snapshot.createdX).toBe(280)
      expect(snapshot.existingX).toBeGreaterThanOrEqual(snapshot.createdX + snapshot.createdWidth)
    } finally {
      await electronApp.close()
    }
  })
})
