import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  dragLocatorTo,
  launchApp,
  storageKey,
  testWorkspacePath,
} from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Spaces (Anchors & Directory Guards)', () => {
  test('creates new tasks in the space under the cursor (right-click anchor)', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-anchor-placeholder',
            title: 'placeholder-task',
            position: { x: 420, y: 260 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'placeholder',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
        ],
        {
          spaces: [
            {
              id: 'space-anchor',
              name: 'Anchor Scope',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-anchor-placeholder'],
              rect: { x: 340, y: 200, width: 700, height: 520 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 380, y: 240 },
      })
      await window.locator('[data-testid="workspace-context-new-task"]').click()

      await expect(window.locator('[data-testid="workspace-task-creator"]')).toBeVisible()
      await window.locator('[data-testid="workspace-task-advanced-toggle"]').click()
      await window.locator('[data-testid="workspace-task-title"]').fill('Anchored Task')
      await window
        .locator('[data-testid="workspace-task-requirement"]')
        .fill('Created inside space anchor')
      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      await expect(window.locator('.task-node')).toHaveCount(2)

      const belongs = await window.evaluate(
        async ({ key, spaceId }) => {
          void key

          const raw = await window.coveApi.persistence.readWorkspaceStateRaw()
          if (!raw) {
            return null
          }

          const parsed = JSON.parse(raw) as {
            workspaces?: Array<{
              nodes?: Array<{ id?: string; kind?: string; task?: { requirement?: string } | null }>
              spaces?: Array<{ id?: string; nodeIds?: string[] }>
            }>
          }

          const workspace = parsed.workspaces?.[0]
          if (!workspace) {
            return null
          }

          const createdTask = (workspace.nodes ?? []).find(
            node =>
              node.kind === 'task' && node.task?.requirement === 'Created inside space anchor',
          )
          const space = (workspace.spaces ?? []).find(item => item.id === spaceId)

          return createdTask?.id && Array.isArray(space?.nodeIds)
            ? space?.nodeIds.includes(createdTask.id)
            : null
        },
        { key: storageKey, spaceId: 'space-anchor' },
      )

      expect(belongs).toBe(true)
    } finally {
      await electronApp.close()
    }
  })

  test('prevents agent windows from entering a space with a different directory', async () => {
    const { electronApp, window } = await launchApp()

    try {
      const worktreePath = `${testWorkspacePath}/.cove/worktrees/wt-ownership`

      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-placeholder-task',
            title: 'task-in-space',
            position: { x: 720, y: 240 },
            width: 360,
            height: 220,
            kind: 'task',
            status: null,
            task: {
              requirement: 'placeholder',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'mismatch-agent',
            title: 'codex · gpt-5.2-codex',
            position: { x: 120, y: 120 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'running',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'dir mismatch test',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: null,
            },
          },
        ],
        {
          spaces: [
            {
              id: 'space-worktree',
              name: 'Worktree Scope',
              directoryPath: worktreePath,
              nodeIds: ['space-placeholder-task'],
              rect: { x: 680, y: 200, width: 520, height: 360 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()
      const paneBox = await pane.boundingBox()
      const spaceRegion = window.locator('.workspace-space-region').first()
      await expect(spaceRegion).toBeVisible()
      const spaceBox = await spaceRegion.boundingBox()
      if (!paneBox || !spaceBox) {
        throw new Error('pane/space bounding box unavailable')
      }

      const agentNode = window
        .locator('.terminal-node')
        .filter({ hasText: 'codex · gpt-5.2-codex' })
        .first()
      await expect(agentNode).toBeVisible()
      await expect(agentNode.locator('.terminal-node__badge--warning')).toHaveCount(0)

      await dragLocatorTo(window, agentNode.locator('.terminal-node__header'), pane, {
        sourcePosition: { x: 80, y: 16 },
        targetPosition: {
          x: spaceBox.x - paneBox.x + spaceBox.width / 2,
          y: spaceBox.y - paneBox.y + spaceBox.height / 2,
        },
      })

      await expect(window.locator('[data-testid="app-message"]')).toContainText(
        'Agent windows cannot enter or leave a space with a different directory.',
      )

      await expect(agentNode.locator('.terminal-node__badge--warning')).toHaveCount(0)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key, nodeId, spaceId }) => {
              void key

              const raw = await window.coveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{
                    id?: string
                    position?: { x?: number; y?: number }
                    agent?: {
                      expectedDirectory?: string | null
                    } | null
                  }>
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const workspace = parsed.workspaces?.[0]
              const node = workspace?.nodes?.find(item => item.id === nodeId)
              const space = workspace?.spaces?.find(item => item.id === spaceId)

              return {
                expectedDirectory: node?.agent?.expectedDirectory ?? null,
                belongsToTarget: space?.nodeIds?.includes(nodeId) ?? false,
              }
            },
            { key: storageKey, nodeId: 'mismatch-agent', spaceId: 'space-worktree' },
          )
        })
        .toEqual({
          expectedDirectory: testWorkspacePath,
          belongsToTarget: false,
        })
    } finally {
      await electronApp.close()
    }
  })

  test('allows moving a task when its linked agent is inactive', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'inactive-task',
            title: 'movable-task',
            position: { x: 120, y: 120 },
            width: 420,
            height: 260,
            kind: 'task',
            status: null,
            task: {
              requirement: 'inactive agent task',
              status: 'todo',
              priority: 'medium',
              tags: [],
              linkedAgentNodeId: 'inactive-agent',
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'inactive-agent',
            title: 'codex · inactive',
            position: { x: 620, y: 120 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'exited',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: '2026-02-09T00:10:00.000Z',
            exitCode: 0,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'inactive',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: 'session-inactive',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: 'inactive-task',
            },
          },
        ],
        { activeSpaceId: null },
      )

      const taskNode = window.locator('.task-node').filter({ hasText: 'movable-task' }).first()
      await expect(taskNode).toBeVisible()

      await taskNode.click()
      await taskNode.click({ button: 'right' })
      await window.locator('[data-testid="workspace-selection-create-space"]').click()

      await expect(window.locator('.workspace-space-region')).toHaveCount(1)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key, nodeId, agentNodeId }) => {
              void key

              const raw = await window.coveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const spaces = parsed.workspaces?.[0]?.spaces ?? []
              const owningSpace = spaces.find(space => space.nodeIds?.includes(nodeId))

              return {
                spaceCount: spaces.length,
                taskOwned: Boolean(owningSpace),
                movedLinkedAgentWithTask: owningSpace?.nodeIds?.includes(agentNodeId) ?? false,
              }
            },
            { key: storageKey, nodeId: 'inactive-task', agentNodeId: 'inactive-agent' },
          )
        })
        .toEqual({
          spaceCount: 1,
          taskOwned: true,
          movedLinkedAgentWithTask: false,
        })
    } finally {
      await electronApp.close()
    }
  })

  test('prevents moving a task when its linked agent is active', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'active-task',
            title: 'blocked-task',
            position: { x: 120, y: 120 },
            width: 420,
            height: 260,
            kind: 'task',
            status: null,
            task: {
              requirement: 'active agent task',
              status: 'doing',
              priority: 'medium',
              tags: [],
              linkedAgentNodeId: 'active-agent',
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'active-agent',
            title: 'codex · active',
            position: { x: 620, y: 120 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'standby',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'active',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: 'session-active',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: 'active-task',
            },
          },
        ],
        { activeSpaceId: null },
      )

      const taskNode = window.locator('.task-node').filter({ hasText: 'blocked-task' }).first()
      await expect(taskNode).toBeVisible()

      await taskNode.click()
      await taskNode.click({ button: 'right' })
      await window.locator('[data-testid="workspace-selection-create-space"]').click()

      await expect(window.locator('[data-testid="app-message"]')).toContainText(
        'Tasks with active agents cannot be moved between spaces.',
      )

      await expect(window.locator('.workspace-space-region')).toHaveCount(0)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key }) => {
              void key

              const raw = await window.coveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{ id?: string; position?: { x?: number; y?: number } }>
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const workspace = parsed.workspaces?.[0]

              return {
                spaceCount: workspace?.spaces?.length ?? 0,
              }
            },
            { key: storageKey },
          )
        })
        .toEqual({
          spaceCount: 0,
        })
    } finally {
      await electronApp.close()
    }
  })
})
