import { expect, test } from '@playwright/test'
import {
  clearAndSeedWorkspace,
  dragLocatorTo,
  launchApp,
  storageKey,
  testWorkspacePath,
} from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Spaces (Anchors & Directory Guards)', () => {
  test('creates new tasks in the space under the cursor (right-click anchor)', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-anchor-placeholder',
            title: 'placeholder-task',
            position: { x: 420, y: 260 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'placeholder',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
        ],
        {
          spaces: [
            {
              id: 'space-anchor',
              name: 'Anchor Scope',
              directoryPath: testWorkspacePath,
              nodeIds: ['space-anchor-placeholder'],
              rect: { x: 340, y: 200, width: 1200, height: 1200 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: { x: 380, y: 240 },
      })
      await window.locator('[data-testid="workspace-context-new-task"]').click()

      await expect(window.locator('[data-testid="workspace-task-creator"]')).toBeVisible()
      await window.locator('[data-testid="workspace-task-advanced-toggle"]').click()
      await window.locator('[data-testid="workspace-task-title"]').fill('Anchored Task')
      await window
        .locator('[data-testid="workspace-task-requirement"]')
        .fill('Created inside space anchor')
      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      await expect(window.locator('.task-node')).toHaveCount(2)

      const belongs = await window.evaluate(
        async ({ key, spaceId }) => {
          void key

          const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
          if (!raw) {
            return null
          }

          const parsed = JSON.parse(raw) as {
            workspaces?: Array<{
              nodes?: Array<{ id?: string; kind?: string; task?: { requirement?: string } | null }>
              spaces?: Array<{ id?: string; nodeIds?: string[] }>
            }>
          }

          const workspace = parsed.workspaces?.[0]
          if (!workspace) {
            return null
          }

          const createdTask = (workspace.nodes ?? []).find(
            node =>
              node.kind === 'task' && node.task?.requirement === 'Created inside space anchor',
          )
          const space = (workspace.spaces ?? []).find(item => item.id === spaceId)

          return createdTask?.id && Array.isArray(space?.nodeIds)
            ? space?.nodeIds.includes(createdTask.id)
            : null
        },
        { key: storageKey, spaceId: 'space-anchor' },
      )

      expect(belongs).toBe(true)
    } finally {
      await electronApp.close()
    }
  })

  test('warns before moving agent windows into a space with a different directory', async () => {
    const { electronApp, window } = await launchApp()

    try {
      const worktreePath = `${testWorkspacePath}/.opencove/worktrees/wt-ownership`

      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-placeholder-task',
            title: 'task-in-space',
            position: { x: 720, y: 240 },
            width: 360,
            height: 220,
            kind: 'task',
            status: null,
            task: {
              requirement: 'placeholder',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'mismatch-agent',
            title: 'codex · gpt-5.2-codex',
            position: { x: 120, y: 120 },
            width: 520,
            height: 320,
            kind: 'agent',
            status: 'running',
            startedAt: '2026-02-09T00:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'dir mismatch test',
              model: 'gpt-5.2-codex',
              effectiveModel: 'gpt-5.2-codex',
              launchMode: 'resume',
              resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
              executionDirectory: testWorkspacePath,
              expectedDirectory: testWorkspacePath,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: null,
            },
          },
        ],
        {
          spaces: [
            {
              id: 'space-worktree',
              name: 'Worktree Scope',
              directoryPath: worktreePath,
              nodeIds: ['space-placeholder-task'],
              rect: { x: 680, y: 200, width: 520, height: 360 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const spaceRegion = window.locator('.workspace-space-region').first()
      await expect(spaceRegion).toBeVisible()
      const spaceBox = await spaceRegion.boundingBox()
      if (!spaceBox) {
        throw new Error('space bounding box unavailable')
      }

      const agentNode = window
        .locator('.terminal-node')
        .filter({ hasText: 'codex · gpt-5.2-codex' })
        .first()
      await expect(agentNode).toBeVisible()
      await expect(agentNode.locator('.terminal-node__badge--warning')).toHaveCount(0)

      await dragLocatorTo(window, agentNode.locator('.terminal-node__header'), spaceRegion, {
        sourcePosition: { x: 80, y: 16 },
        targetPosition: {
          x: Math.min(Math.max(140, Math.round(spaceBox.width * 0.35)), spaceBox.width - 40),
          y: Math.min(Math.max(140, Math.round(spaceBox.height * 0.45)), spaceBox.height - 40),
        },
        steps: 18,
      })

      const warningWindow = window.locator('[data-testid="space-worktree-mismatch-drop-warning"]')
      await expect(warningWindow).toBeVisible()
      await expect(agentNode.locator('.terminal-node__badge--warning')).toHaveCount(0)
      await warningWindow
        .locator('[data-testid="space-worktree-mismatch-drop-warning-continue"]')
        .click()
      await expect(warningWindow).toBeHidden()
      await expect(agentNode.locator('.terminal-node__badge--warning')).toHaveCount(1)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key, nodeId, spaceId }) => {
              void key

              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{
                    id?: string
                    position?: { x?: number; y?: number }
                    agent?: {
                      expectedDirectory?: string | null
                    } | null
                  }>
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const workspace = parsed.workspaces?.[0]
              const node = workspace?.nodes?.find(item => item.id === nodeId)
              const space = workspace?.spaces?.find(item => item.id === spaceId)

              return {
                expectedDirectory: node?.agent?.expectedDirectory ?? null,
                belongsToTarget: space?.nodeIds?.includes(nodeId) ?? false,
              }
            },
            { key: storageKey, nodeId: 'mismatch-agent', spaceId: 'space-worktree' },
          )
        })
        .toEqual({
          expectedDirectory: worktreePath,
          belongsToTarget: true,
        })
    } finally {
      await electronApp.close()
    }
  })

  test('warns before moving terminal windows from a worktree space back to workspace root', async () => {
    const { electronApp, window } = await launchApp()

    try {
      const worktreePath = `${testWorkspacePath}/.opencove/worktrees/wt-root-warning`

      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'space-root-warning-placeholder',
            title: 'task-in-worktree-space',
            position: { x: 760, y: 240 },
            width: 360,
            height: 220,
            kind: 'task',
            status: null,
            task: {
              requirement: 'placeholder',
              status: 'todo',
              priority: 'low',
              tags: [],
              linkedAgentNodeId: null,
              agentSessions: [],
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-02-09T00:00:00.000Z',
              updatedAt: '2026-02-09T00:00:00.000Z',
            },
          },
          {
            id: 'worktree-terminal',
            title: 'terminal-worktree',
            position: { x: 820, y: 320 },
            width: 520,
            height: 320,
            kind: 'terminal',
            status: 'standby',
            executionDirectory: worktreePath,
            expectedDirectory: worktreePath,
          },
        ],
        {
          spaces: [
            {
              id: 'space-worktree-root-warning',
              name: 'Worktree Scope',
              directoryPath: worktreePath,
              nodeIds: ['space-root-warning-placeholder', 'worktree-terminal'],
              rect: { x: 700, y: 200, width: 620, height: 460 },
            },
          ],
          activeSpaceId: null,
        },
      )

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      const terminalNode = window
        .locator('.terminal-node')
        .filter({ hasText: 'terminal-worktree' })
        .first()
      await expect(terminalNode).toBeVisible()
      await expect(terminalNode.locator('.terminal-node__badge--warning')).toHaveCount(0)

      await dragLocatorTo(window, terminalNode.locator('.terminal-node__header'), pane, {
        sourcePosition: { x: 80, y: 16 },
        targetPosition: { x: 140, y: 120 },
        steps: 18,
      })

      const warningWindow = window.locator('[data-testid="space-worktree-mismatch-drop-warning"]')
      await expect(warningWindow).toBeVisible()
      await expect(terminalNode.locator('.terminal-node__badge--warning')).toHaveCount(0)
      await warningWindow
        .locator('[data-testid="space-worktree-mismatch-drop-warning-continue"]')
        .click()
      await expect(warningWindow).toBeHidden()
      await expect(terminalNode.locator('.terminal-node__badge--warning')).toHaveCount(1)

      await expect
        .poll(async () => {
          return await window.evaluate(
            async ({ key, nodeId, spaceId }) => {
              void key

              const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
              if (!raw) {
                return null
              }

              const parsed = JSON.parse(raw) as {
                workspaces?: Array<{
                  nodes?: Array<{
                    id?: string
                    executionDirectory?: string | null
                    expectedDirectory?: string | null
                  }>
                  spaces?: Array<{ id?: string; nodeIds?: string[] }>
                }>
              }

              const workspace = parsed.workspaces?.[0]
              const node = workspace?.nodes?.find(item => item.id === nodeId)
              const space = workspace?.spaces?.find(item => item.id === spaceId)

              return {
                executionDirectory: node?.executionDirectory ?? null,
                expectedDirectory: node?.expectedDirectory ?? null,
                belongsToWorktreeSpace: space?.nodeIds?.includes(nodeId) ?? false,
              }
            },
            {
              key: storageKey,
              nodeId: 'worktree-terminal',
              spaceId: 'space-worktree-root-warning',
            },
          )
        })
        .toEqual({
          executionDirectory: worktreePath,
          expectedDirectory: testWorkspacePath,
          belongsToWorktreeSpace: false,
        })
    } finally {
      await electronApp.close()
    }
  })
})
