import type { Node } from '@xyflow/react'
import type { AgentSettings, AgentProvider } from '../settings/agentConfig'

export type WorkspaceNodeKind = 'terminal' | 'agent' | 'task'

export type AgentRuntimeStatus =
  | 'running'
  | 'standby'
  | 'exited'
  | 'failed'
  | 'stopped'
  | 'restoring'

export type TaskRuntimeStatus = 'todo' | 'doing' | 'ai_done' | 'done'

export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent'

export type AgentLaunchMode = 'new' | 'resume'

export type ExecutionDirectoryMode = 'workspace' | 'custom'

export interface TaskAgentSessionRecord {
  id: string
  provider: AgentProvider
  resumeSessionId: string | null
  prompt: string
  model: string | null
  effectiveModel: string | null
  boundDirectory: string
  lastDirectory: string
  createdAt: string
  lastRunAt: string
  endedAt: string | null
  exitCode: number | null
  status: AgentRuntimeStatus
}

export interface AgentNodeData {
  provider: AgentProvider
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: AgentLaunchMode
  resumeSessionId: string | null
  executionDirectory: string
  expectedDirectory: string | null
  directoryMode: ExecutionDirectoryMode
  customDirectory: string | null
  shouldCreateDirectory: boolean
  taskId: string | null
}

export interface TaskNodeData {
  requirement: string
  status: TaskRuntimeStatus
  priority: TaskPriority
  tags: string[]
  linkedAgentNodeId: string | null
  agentSessions: TaskAgentSessionRecord[]
  lastRunAt: string | null
  autoGeneratedTitle: boolean
  isEnriching?: boolean
  createdAt: string | null
  updatedAt: string | null
}

export interface TerminalNodeData {
  [key: string]: unknown
  sessionId: string
  title: string
  titlePinnedByUser?: boolean
  width: number
  height: number
  kind: WorkspaceNodeKind
  status: AgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  scrollback: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent: AgentNodeData | null
  task: TaskNodeData | null
}

export interface WorkspaceState {
  id: string
  name: string
  path: string
  worktreesRoot: string
  nodes: Node<TerminalNodeData>[]
  viewport: WorkspaceViewport
  isMinimapVisible: boolean
  spaces: WorkspaceSpaceState[]
  activeSpaceId: string | null
}

export interface PersistedWorkspaceState {
  id: string
  name: string
  path: string
  worktreesRoot: string
  nodes: PersistedTerminalNode[]
  viewport: WorkspaceViewport
  isMinimapVisible: boolean
  spaces: WorkspaceSpaceState[]
  activeSpaceId: string | null
}

export interface WorkspaceSpaceRect {
  x: number
  y: number
  width: number
  height: number
}

export interface WorkspaceSpaceState {
  id: string
  name: string
  directoryPath: string
  nodeIds: string[]
  rect: WorkspaceSpaceRect | null
}

export interface PersistedTerminalNode {
  id: string
  title: string
  titlePinnedByUser?: boolean
  position: Point
  width: number
  height: number
  kind: WorkspaceNodeKind
  status: AgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  scrollback: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent: AgentNodeData | null
  task: TaskNodeData | null
}

export interface PersistedAppState {
  formatVersion: number
  activeWorkspaceId: string | null
  workspaces: PersistedWorkspaceState[]
  settings: AgentSettings
}

export interface WorkspaceViewport {
  x: number
  y: number
  zoom: number
}

export const DEFAULT_WORKSPACE_VIEWPORT: WorkspaceViewport = {
  x: 0,
  y: 0,
  zoom: 1,
}

export const DEFAULT_WORKSPACE_MINIMAP_VISIBLE = true

export interface Size {
  width: number
  height: number
}

export interface Point {
  x: number
  y: number
}
