export const IPC_CHANNELS = {
  workspaceSelectDirectory: 'workspace:select-directory',
  workspaceEnsureDirectory: 'workspace:ensure-directory',
  workspaceCopyPath: 'workspace:copy-path',
  workspaceListPathOpeners: 'workspace:list-path-openers',
  workspaceOpenPath: 'workspace:open-path',
  persistenceReadWorkspaceStateRaw: 'persistence:read-workspace-state-raw',
  persistenceWriteWorkspaceStateRaw: 'persistence:write-workspace-state-raw',
  persistenceReadAppState: 'persistence:read-app-state',
  persistenceWriteAppState: 'persistence:write-app-state',
  persistenceReadNodeScrollback: 'persistence:read-node-scrollback',
  persistenceWriteNodeScrollback: 'persistence:write-node-scrollback',
  worktreeListBranches: 'worktree:list-branches',
  worktreeListWorktrees: 'worktree:list-worktrees',
  worktreeCreate: 'worktree:create',
  worktreeRemove: 'worktree:remove',
  worktreeRenameBranch: 'worktree:rename-branch',
  worktreeSuggestNames: 'worktree:suggest-names',
  ptySpawn: 'pty:spawn',
  ptyWrite: 'pty:write',
  ptyResize: 'pty:resize',
  ptyKill: 'pty:kill',
  ptyAttach: 'pty:attach',
  ptyDetach: 'pty:detach',
  ptySnapshot: 'pty:snapshot',
  ptyData: 'pty:data',
  ptyExit: 'pty:exit',
  ptyState: 'pty:state',
  ptySessionMetadata: 'pty:session-metadata',
  agentListModels: 'agent:list-models',
  agentLaunch: 'agent:launch',
  taskSuggestTitle: 'task:suggest-title',
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
