import { describe, expect, it, vi } from 'vitest'
import type { Node } from '@xyflow/react'
import { DEFAULT_AGENT_SETTINGS } from '../../../src/contexts/settings/domain/agentSettings'
import { resolveDefaultAgentLaunchGeometry } from '../../../src/contexts/workspace/presentation/renderer/components/workspaceCanvas/hooks/agentLaunchGeometry'
import type {
  TerminalNodeData,
  WorkspaceSpaceState,
} from '../../../src/contexts/workspace/presentation/renderer/types'
import { runTaskAgentAction } from '../../../src/contexts/workspace/presentation/renderer/components/workspaceCanvas/hooks/useTaskActions.agentSession'

describe('WorkspaceCanvas task run agent auto resize', () => {
  const terminalDisplayMetrics = {
    fontSize: DEFAULT_AGENT_SETTINGS.terminalFontSize,
    lineHeight: 1,
    letterSpacing: 0,
  }

  function expectedAgentGeometry() {
    return resolveDefaultAgentLaunchGeometry({
      bucket: DEFAULT_AGENT_SETTINGS.standardWindowSizeBucket,
      terminalFontSize: DEFAULT_AGENT_SETTINGS.terminalFontSize,
    }).terminalGeometry
  }

  it('expands the task space to fit the created agent node', async () => {
    const launch = vi.fn(async () => ({
      sessionId: 'agent-session-1',
      provider: 'codex' as const,
      command: 'codex',
      args: [],
      launchMode: 'new' as const,
      effectiveModel: 'model',
      resumeSessionId: null,
    }))

    Object.defineProperty(window, 'opencoveApi', {
      configurable: true,
      writable: true,
      value: {
        agent: {
          launch,
        },
      },
    })

    const now = new Date().toISOString()

    const taskNode: Node<TerminalNodeData> = {
      id: 'task-1',
      type: 'taskNode',
      position: { x: 0, y: 0 },
      data: {
        sessionId: '',
        title: 'Task',
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        startedAt: null,
        endedAt: null,
        exitCode: null,
        lastError: null,
        scrollback: null,
        agent: null,
        task: {
          requirement: 'Implement feature',
          status: 'todo',
          priority: 'medium',
          tags: [],
          linkedAgentNodeId: null,
          agentSessions: [],
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: now,
          updatedAt: now,
        },
      },
      draggable: true,
      selectable: true,
    }

    const initialRect = { x: -24, y: -24, width: 508, height: 328 }
    const spaces: WorkspaceSpaceState[] = [
      {
        id: 'space-1',
        name: 'Space',
        directoryPath: '/tmp',
        targetMountId: null,
        labelColor: null,
        nodeIds: [taskNode.id],
        rect: initialRect,
      },
    ]

    const nodesRef = { current: [taskNode] }
    const spacesRef = { current: spaces }

    const onSpacesChange = vi.fn((nextSpaces: WorkspaceSpaceState[]) => {
      spacesRef.current = nextSpaces
    })

    const setNodes = (
      updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    ) => {
      nodesRef.current = updater(nodesRef.current)
    }

    await runTaskAgentAction(taskNode.id, {
      nodesRef,
      spacesRef,
      onSpacesChange,
      setNodes,
      createNodeForSession: async input => {
        const created: Node<TerminalNodeData> = {
          id: 'agent-1',
          type: 'terminalNode',
          position: input.anchor,
          data: {
            sessionId: input.sessionId,
            title: input.title,
            width: 520,
            height: 400,
            kind: 'agent',
            status: 'running',
            startedAt: now,
            endedAt: null,
            exitCode: null,
            lastError: null,
            scrollback: null,
            agent: input.agent ?? null,
            task: null,
            note: null,
          },
          draggable: true,
          selectable: true,
        }

        setNodes(prev => [...prev, created])
        return created
      },
      buildAgentNodeTitle: () => 'codex · model',
      launchAgentInNode: vi.fn(async () => undefined),
      agentSettings: DEFAULT_AGENT_SETTINGS,
      terminalDisplayMetrics,
      workspacePath: '/tmp',
      onRequestPersistFlush: vi.fn(),
    })
    const geometry = expectedAgentGeometry()

    expect(launch).toHaveBeenCalledWith(expect.objectContaining(geometry))
    expect(onSpacesChange).toHaveBeenCalled()

    const nextSpace = spacesRef.current.find(space => space.id === 'space-1')
    expect(nextSpace).toBeTruthy()
    expect(nextSpace?.nodeIds).toEqual(expect.arrayContaining(['task-1', 'agent-1']))
    expect(nextSpace?.rect?.width).toBeGreaterThan(initialRect.width)
    expect(nextSpace?.rect?.height).toBeGreaterThan(initialRect.height)
  })

  it('persists mounted task agents with the launched runtime metadata instead of the default profile', async () => {
    const now = new Date().toISOString()
    const controlSurfaceInvoke = vi.fn(async request => {
      if (request.id === 'mount.list') {
        return {
          mounts: [
            {
              mountId: 'mount-local',
              endpointId: 'local',
              targetId: 'target-local',
              rootPath: '/tmp',
              rootUri: 'file:///tmp',
              name: 'tmp',
            },
          ],
        }
      }

      if (request.id === 'session.launchAgentInMount') {
        return {
          sessionId: 'mounted-session-1',
          provider: 'codex' as const,
          startedAt: now,
          executionContext: {
            projectId: 'workspace-1',
            spaceId: null,
            mountId: 'mount-local',
            targetId: 'target-local',
            endpoint: {
              endpointId: 'local',
              kind: 'local' as const,
            },
            target: {
              scheme: 'file' as const,
              rootPath: '/tmp',
              rootUri: 'file:///tmp',
            },
            scope: {
              rootPath: '/tmp',
              rootUri: 'file:///tmp',
            },
            workingDirectory: '/tmp',
          },
          profileId: null,
          runtimeKind: 'windows' as const,
          resumeSessionId: null,
          effectiveModel: 'gpt-5.2-codex',
          command: 'cmd.exe',
          args: ['/d', '/c', 'codex.cmd'],
        }
      }

      throw new Error(`Unexpected control surface command: ${String(request.id)}`)
    })

    Object.defineProperty(window, 'opencoveApi', {
      configurable: true,
      writable: true,
      value: {
        controlSurface: {
          invoke: controlSurfaceInvoke,
        },
      },
    })

    const taskNode: Node<TerminalNodeData> = {
      id: 'task-mounted-1',
      type: 'taskNode',
      position: { x: 0, y: 0 },
      data: {
        sessionId: '',
        title: 'Mounted task',
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        startedAt: null,
        endedAt: null,
        exitCode: null,
        lastError: null,
        scrollback: null,
        agent: null,
        task: {
          requirement: 'Launch mounted task agent',
          status: 'todo',
          priority: 'medium',
          tags: [],
          linkedAgentNodeId: null,
          agentSessions: [],
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: now,
          updatedAt: now,
        },
      },
      draggable: true,
      selectable: true,
    }

    const nodesRef = { current: [taskNode] }
    const spacesRef = {
      current: [] as WorkspaceSpaceState[],
    }

    const setNodes = (
      updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    ) => {
      nodesRef.current = updater(nodesRef.current)
    }

    const createNodeForSession = vi.fn(async input => {
      const created: Node<TerminalNodeData> = {
        id: 'agent-mounted-1',
        type: 'terminalNode',
        position: input.anchor,
        data: {
          sessionId: input.sessionId,
          profileId: input.profileId ?? null,
          runtimeKind: input.runtimeKind ?? null,
          title: input.title,
          width: 520,
          height: 400,
          kind: 'agent',
          status: 'running',
          startedAt: now,
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: null,
          agent: input.agent ?? null,
          task: null,
          note: null,
        },
        draggable: true,
        selectable: true,
      }

      setNodes(prev => [...prev, created])
      return created
    })

    await runTaskAgentAction(taskNode.id, {
      nodesRef,
      spacesRef,
      onSpacesChange: vi.fn(),
      setNodes,
      createNodeForSession,
      buildAgentNodeTitle: () => 'codex · gpt-5.2-codex',
      launchAgentInNode: vi.fn(async () => undefined),
      agentSettings: {
        ...DEFAULT_AGENT_SETTINGS,
        defaultTerminalProfileId: 'wsl:Ubuntu',
      },
      terminalDisplayMetrics,
      workspaceId: 'workspace-1',
      workspacePath: '/tmp',
      onRequestPersistFlush: vi.fn(),
    })
    const geometry = expectedAgentGeometry()

    expect(controlSurfaceInvoke).toHaveBeenCalledWith(
      expect.objectContaining({
        id: 'session.launchAgentInMount',
        payload: expect.objectContaining(geometry),
      }),
    )
    expect(createNodeForSession).toHaveBeenCalledWith(
      expect.objectContaining({
        sessionId: 'mounted-session-1',
        profileId: null,
        runtimeKind: 'windows',
        terminalGeometry: geometry,
      }),
    )
  })
})
