import React, { useRef, useState } from 'react'
import { fireEvent, render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import type { Node } from '@xyflow/react'
import { useWorkspaceCanvasSpaceDirectoryOps } from '../../../src/renderer/src/features/workspace/components/workspaceCanvas/hooks/useSpaceDirectoryOps'
import type {
  TerminalNodeData,
  WorkspaceSpaceState,
} from '../../../src/renderer/src/features/workspace/types'

function createNoteNode(id: string, title: string): Node<TerminalNodeData> {
  return {
    id,
    type: 'noteNode',
    position: { x: 0, y: 0 },
    data: {
      sessionId: '',
      title,
      width: 320,
      height: 220,
      kind: 'note',
      status: null,
      startedAt: null,
      endedAt: null,
      exitCode: null,
      lastError: null,
      scrollback: null,
      agent: null,
      task: null,
      note: { text: `${title} body` },
    },
    draggable: true,
    selectable: true,
  }
}

function createTaskNode(id: string, title: string): Node<TerminalNodeData> {
  return {
    id,
    type: 'taskNode',
    position: { x: 40, y: 40 },
    data: {
      sessionId: '',
      title,
      width: 360,
      height: 240,
      kind: 'task',
      status: null,
      startedAt: null,
      endedAt: null,
      exitCode: null,
      lastError: null,
      scrollback: null,
      executionDirectory: null,
      expectedDirectory: null,
      agent: null,
      task: {
        requirement: 'Do the thing',
        status: 'todo',
        priority: 'medium',
        tags: [],
        linkedAgentNodeId: null,
        agentSessions: [],
        lastRunAt: null,
        autoGeneratedTitle: false,
        createdAt: null,
        updatedAt: null,
      },
      note: null,
    },
    draggable: true,
    selectable: true,
  }
}

describe('useWorkspaceCanvasSpaceDirectoryOps archiveSpace', () => {
  it('removes the archived space and all nodes inside it', () => {
    const onRequestPersistFlush = vi.fn()
    const closeNode = vi.fn(async () => undefined)

    const initialNodes: Node<TerminalNodeData>[] = [
      createTaskNode('task-1', 'Task 1'),
      createNoteNode('note-1', 'Note 1'),
      createNoteNode('outside-note', 'Outside Note'),
    ]

    const initialSpaces: WorkspaceSpaceState[] = [
      {
        id: 'space-1',
        name: 'Space 1',
        directoryPath: '/repo/.cove/worktrees/space-1',
        nodeIds: ['task-1', 'note-1'],
        rect: null,
      },
    ]

    function Harness() {
      const [nodes, setNodesState] = useState(initialNodes)
      const [spaces, setSpacesState] = useState(initialSpaces)
      const nodesRef = useRef(nodes)
      const spacesRef = useRef(spaces)

      nodesRef.current = nodes
      spacesRef.current = spaces

      const { updateSpaceDirectory } = useWorkspaceCanvasSpaceDirectoryOps({
        workspacePath: '/repo',
        spacesRef,
        nodesRef,
        setNodes: updater => {
          setNodesState(prevNodes => {
            const nextNodes = updater(prevNodes)
            nodesRef.current = nextNodes
            return nextNodes
          })
        },
        onSpacesChange: nextSpaces => {
          spacesRef.current = nextSpaces
          setSpacesState(nextSpaces)
        },
        onRequestPersistFlush,
        closeNode,
      })

      return (
        <div>
          <div data-testid="node-count">{nodes.length}</div>
          <div data-testid="space-count">{spaces.length}</div>
          <div data-testid="titles">{nodes.map(node => node.data.title).join(', ')}</div>
          <button
            type="button"
            onClick={() => {
              updateSpaceDirectory('space-1', '/repo', { archiveSpace: true })
            }}
          >
            Archive Space
          </button>
        </div>
      )
    }

    render(<Harness />)

    fireEvent.click(screen.getByRole('button', { name: 'Archive Space' }))

    expect(screen.getByTestId('space-count')).toHaveTextContent('0')
    expect(screen.getByTestId('node-count')).toHaveTextContent('1')
    expect(screen.getByTestId('titles')).toHaveTextContent('Outside Note')
    expect(screen.getByTestId('titles')).not.toHaveTextContent('Task 1')
    expect(screen.getByTestId('titles')).not.toHaveTextContent('Note 1')
    expect(closeNode).not.toHaveBeenCalled()
    expect(onRequestPersistFlush).toHaveBeenCalledTimes(1)
  })
})
