import { describe, expect, it, vi } from 'vitest'
import type { Node } from '@xyflow/react'
import { DEFAULT_AGENT_SETTINGS } from '../../../src/renderer/src/features/settings/agentConfig'
import type {
  TerminalNodeData,
  WorkspaceSpaceState,
} from '../../../src/renderer/src/features/workspace/types'
import { runTaskAgentAction } from '../../../src/renderer/src/features/workspace/components/workspaceCanvas/hooks/useTaskActions.agentSession'

describe('WorkspaceCanvas task run agent auto resize', () => {
  it('expands the task space to fit the created agent node', async () => {
    const launch = vi.fn(async () => ({
      sessionId: 'agent-session-1',
      provider: 'codex' as const,
      command: 'codex',
      args: [],
      launchMode: 'new' as const,
      effectiveModel: 'model',
      resumeSessionId: null,
    }))

    Object.defineProperty(window, 'coveApi', {
      configurable: true,
      writable: true,
      value: {
        agent: {
          launch,
        },
      },
    })

    const now = new Date().toISOString()

    const taskNode: Node<TerminalNodeData> = {
      id: 'task-1',
      type: 'taskNode',
      position: { x: 0, y: 0 },
      data: {
        sessionId: '',
        title: 'Task',
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        startedAt: null,
        endedAt: null,
        exitCode: null,
        lastError: null,
        scrollback: null,
        agent: null,
        task: {
          requirement: 'Implement feature',
          status: 'todo',
          priority: 'medium',
          tags: [],
          linkedAgentNodeId: null,
          agentSessions: [],
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: now,
          updatedAt: now,
        },
      },
      draggable: true,
      selectable: true,
    }

    const initialRect = { x: -24, y: -24, width: 508, height: 328 }
    const spaces: WorkspaceSpaceState[] = [
      {
        id: 'space-1',
        name: 'Space',
        directoryPath: '/tmp',
        nodeIds: [taskNode.id],
        rect: initialRect,
      },
    ]

    const nodesRef = { current: [taskNode] }
    const spacesRef = { current: spaces }

    const onSpacesChange = vi.fn((nextSpaces: WorkspaceSpaceState[]) => {
      spacesRef.current = nextSpaces
    })

    const setNodes = (
      updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    ) => {
      nodesRef.current = updater(nodesRef.current)
    }

    await runTaskAgentAction(taskNode.id, {
      nodesRef,
      spacesRef,
      onSpacesChange,
      setNodes,
      createNodeForSession: async input => {
        const created: Node<TerminalNodeData> = {
          id: 'agent-1',
          type: 'terminalNode',
          position: input.anchor,
          data: {
            sessionId: input.sessionId,
            title: input.title,
            width: 520,
            height: 400,
            kind: 'agent',
            status: 'running',
            startedAt: now,
            endedAt: null,
            exitCode: null,
            lastError: null,
            scrollback: null,
            agent: input.agent ?? null,
            task: null,
            note: null,
          },
          draggable: true,
          selectable: true,
        }

        setNodes(prev => [...prev, created])
        return created
      },
      buildAgentNodeTitle: () => 'codex · model',
      launchAgentInNode: vi.fn(async () => undefined),
      agentSettings: DEFAULT_AGENT_SETTINGS,
      workspacePath: '/tmp',
      onRequestPersistFlush: vi.fn(),
    })

    expect(onSpacesChange).toHaveBeenCalled()

    const nextSpace = spacesRef.current.find(space => space.id === 'space-1')
    expect(nextSpace).toBeTruthy()
    expect(nextSpace?.nodeIds).toEqual(expect.arrayContaining(['task-1', 'agent-1']))
    expect(nextSpace?.rect?.width).toBeGreaterThan(initialRect.width)
    expect(nextSpace?.rect?.height).toBeGreaterThan(initialRect.height)
  })
})
