import React, { useState } from 'react'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import type { Node } from '@xyflow/react'
import { DEFAULT_AGENT_SETTINGS } from '../../../src/renderer/src/features/settings/agentConfig'
import type {
  TerminalNodeData,
  WorkspaceSpaceState,
  WorkspaceViewport,
} from '../../../src/renderer/src/features/workspace/types'
import { WorkspaceCanvas } from '../../../src/renderer/src/features/workspace/components/WorkspaceCanvas'

vi.mock('@xyflow/react', () => {
  return {
    ReactFlowProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
    useReactFlow: () => ({
      screenToFlowPosition: ({ x, y }: { x: number; y: number }) => ({ x, y }),
      setCenter: vi.fn(),
      getViewport: vi.fn(() => ({ x: 0, y: 0, zoom: 1 })),
      setViewport: vi.fn(),
    }),
    useStoreApi: () => ({
      setState: vi.fn(),
      getState: vi.fn(() => ({})),
      subscribe: vi.fn(),
    }),
    ViewportPortal: ({ children }: { children: React.ReactNode }) => <>{children}</>,
    applyNodeChanges: (_changes: unknown, nodes: unknown) => nodes,
    ReactFlow: ({
      nodes,
      nodeTypes,
    }: {
      nodes: Array<{ id: string; type: string; data: unknown }>
      nodeTypes?: Record<string, React.ComponentType<{ id: string; data: unknown }>>
    }) => {
      return (
        <div>
          {nodes.map(node => {
            const Renderer = nodeTypes?.[node.type]
            if (!Renderer) {
              return null
            }
            return <Renderer key={node.id} id={node.id} data={node.data} />
          })}
        </div>
      )
    },
    Background: () => null,
    Controls: () => null,
    MiniMap: () => null,
    BackgroundVariant: {
      Dots: 'dots',
    },
    SelectionMode: {
      Partial: 'partial',
    },
    MarkerType: {
      ArrowClosed: 'arrowclosed',
    },
    PanOnScrollMode: {
      Free: 'free',
    },
    Handle: () => null,
    Position: {
      Left: 'left',
      Right: 'right',
    },
  }
})

vi.mock('../../../src/renderer/src/features/workspace/components/TerminalNode', () => {
  return {
    TerminalNode: () => null,
  }
})

vi.mock('../../../src/renderer/src/features/workspace/components/TaskNode', () => {
  return {
    TaskNode: ({ onRunAgent }: { onRunAgent?: () => void }) => {
      return (
        <button type="button" data-testid="task-run-agent" onClick={() => onRunAgent?.()}>
          Run Agent
        </button>
      )
    },
  }
})

describe('WorkspaceCanvas task agent directory', () => {
  it('launches task agent in the space directory when the task belongs to a worktree space', async () => {
    const launch = vi.fn(async () => ({
      sessionId: 'new-session',
      provider: 'codex' as const,
      command: 'codex',
      args: [],
      launchMode: 'new' as const,
      effectiveModel: 'model',
      resumeSessionId: 'resume-1',
    }))

    Object.defineProperty(window, 'coveApi', {
      configurable: true,
      writable: true,
      value: {
        pty: {
          kill: vi.fn(async () => undefined),
          onExit: vi.fn(() => () => undefined),
        },
        workspace: {
          ensureDirectory: vi.fn(async () => undefined),
        },
        agent: {
          launch,
        },
        task: {
          suggestTitle: vi.fn(async () => ({
            title: 't',
            provider: 'codex',
            effectiveModel: null,
          })),
        },
      },
    })

    const now = new Date().toISOString()
    const worktreeDirectory = '/tmp/repo/.cove/worktrees/demo'

    const initialNodes: Node<TerminalNodeData>[] = [
      {
        id: 'task-1',
        type: 'taskNode',
        position: { x: 0, y: 0 },
        data: {
          sessionId: '',
          title: 'Task',
          width: 460,
          height: 280,
          kind: 'task',
          status: null,
          startedAt: null,
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: null,
          agent: null,
          task: {
            requirement: 'Implement feature',
            status: 'todo',
            priority: 'medium',
            tags: [],
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: now,
            updatedAt: now,
          },
        },
        draggable: true,
        selectable: true,
      },
    ]

    const viewport: WorkspaceViewport = { x: 0, y: 0, zoom: 1 }
    const spaces: WorkspaceSpaceState[] = [
      {
        id: 'space-1',
        name: 'Worktree Space',
        directoryPath: worktreeDirectory,
        nodeIds: ['task-1'],
        rect: null,
      },
    ]

    function Harness() {
      const [nodes, setNodes] = useState(initialNodes)

      return (
        <WorkspaceCanvas
          workspaceId="workspace-1"
          workspacePath="/tmp/repo"
          worktreesRoot=""
          nodes={nodes}
          onNodesChange={setNodes}
          spaces={spaces}
          activeSpaceId="space-1"
          onSpacesChange={() => undefined}
          onActiveSpaceChange={() => undefined}
          viewport={viewport}
          isMinimapVisible={false}
          onViewportChange={() => undefined}
          onMinimapVisibilityChange={() => undefined}
          agentSettings={DEFAULT_AGENT_SETTINGS}
        />
      )
    }

    render(<Harness />)

    fireEvent.click(screen.getByTestId('task-run-agent'))

    await waitFor(() => {
      expect(launch).toHaveBeenCalledTimes(1)
    })

    expect(launch.mock.calls[0]?.[0]).toEqual(
      expect.objectContaining({
        cwd: worktreeDirectory,
      }),
    )
  })
})
