import type { Node } from '@xyflow/react'
import type {
  AgentNodeData,
  Point,
  TaskPriority,
  TaskRuntimeStatus,
  TerminalNodeData,
  WorkspaceSpaceRect,
  WorkspaceSpaceState,
  WorkspaceViewport,
} from '../../types'
import type { AgentSettings } from '@contexts/settings/domain/agentSettings'

export type WorkspaceCanvasMessageTone = 'info' | 'warning' | 'error'

export type ShowWorkspaceCanvasMessage = (
  message: string,
  tone?: WorkspaceCanvasMessageTone,
) => void

export interface WorkspaceCanvasProps {
  workspaceId: string
  onShowMessage?: ShowWorkspaceCanvasMessage
  workspacePath: string
  worktreesRoot: string
  nodes: Node<TerminalNodeData>[]
  onNodesChange: (nodes: Node<TerminalNodeData>[]) => void
  onRequestPersistFlush?: () => void
  spaces: WorkspaceSpaceState[]
  activeSpaceId: string | null
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onActiveSpaceChange: (spaceId: string | null) => void
  viewport: WorkspaceViewport
  isMinimapVisible: boolean
  onViewportChange: (viewport: WorkspaceViewport) => void
  onMinimapVisibilityChange: (isVisible: boolean) => void
  agentSettings: AgentSettings
  focusNodeId?: string | null
  focusSequence?: number
}

export interface PaneContextMenuState {
  kind: 'pane'
  x: number
  y: number
  flowX: number
  flowY: number
}

export interface SelectionContextMenuState {
  kind: 'selection'
  x: number
  y: number
}

export type ContextMenuState = PaneContextMenuState | SelectionContextMenuState

export interface SpaceActionMenuState {
  spaceId: string
  x: number
  y: number
}

export interface SpaceWorktreeDialogState {
  spaceId: string
  initialViewMode: 'home' | 'create' | 'archive'
}

export interface SelectionDraftState {
  startX: number
  startY: number
  currentX: number
  currentY: number
  additive: boolean
  selectedNodeIdsAtStart: string[]
  selectedSpaceIdsAtStart: string[]
  startSpaceId: string | null
  phase: 'active' | 'settling'
}

export interface EmptySelectionPromptState {
  x: number
  y: number
  rect: WorkspaceSpaceRect
}

export interface SpaceVisual {
  id: string
  name: string
  directoryPath: string
  rect: WorkspaceSpaceRect
  hasExplicitRect: boolean
}

export interface SpaceDragState {
  pointerId: number
  spaceId: string
  startFlow: Point
  initialRect: WorkspaceSpaceRect
  initialNodePositions: Map<string, Point>
  ownedBounds: { left: number; top: number; right: number; bottom: number } | null
  handle:
    | { kind: 'move' }
    | {
        kind: 'resize'
        edges: Partial<Record<'top' | 'right' | 'bottom' | 'left', true>>
      }
}

export type TrackpadGestureAction = 'pan' | 'pinch'
export type TrackpadGestureTarget = 'canvas' | 'node'

export interface TrackpadGestureLockState {
  action: TrackpadGestureAction
  target: TrackpadGestureTarget
  lastTimestamp: number
}

export interface TaskCreatorState {
  anchor: Point
  title: string
  requirement: string
  priority: TaskPriority
  selectedTags: string[]
  autoGenerateTitle: boolean
  isGeneratingTitle: boolean
  isCreating: boolean
  error: string | null
}

export interface TaskEditorState {
  nodeId: string
  initialTitle: string
  initialAutoGeneratedTitle: boolean
  titleGeneratedInEditor: boolean
  title: string
  requirement: string
  priority: TaskPriority
  selectedTags: string[]
  autoGenerateTitle: boolean
  isGeneratingTitle: boolean
  isSaving: boolean
  error: string | null
}

export interface TaskDeleteConfirmationState {
  nodeId: string
  title: string
}

export interface CreateNodeInput {
  sessionId: string
  title: string
  anchor: Point
  kind: 'terminal' | 'agent'
  agent?: AgentNodeData | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
}

export type QuickUpdateTaskTitle = (nodeId: string, title: string) => void
export type QuickUpdateTaskRequirement = (nodeId: string, requirement: string) => void
export type UpdateTaskStatus = (nodeId: string, status: TaskRuntimeStatus) => void
export type UpdateNodeScrollback = (nodeId: string, scrollback: string) => void
